// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const acceleratedLike = `-- name: AcceleratedLike :many
SELECT name
FROM menu_search_lab
WHERE name ILIKE '%presso%'
ORDER BY id
`

// Бонус trgm-индекса: ILIKE '%подстрока%' с шаблоном в середине обычный B-tree
// не ускоряет, а GIN gin_trgm_ops — да (06-05 про индексы). Семантика та же, что
// у обычного ILIKE; ускорение проявляется на большой таблице.
func (q *Queries) AcceleratedLike(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, acceleratedLike)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const didYouMean = `-- name: DidYouMean :many
SELECT name, round(similarity(name, 'capucino')::numeric, 3)::text AS sim
FROM menu_search_lab
WHERE name % 'capucino'
ORDER BY similarity(name, 'capucino') DESC, id
`

type DidYouMeanRow struct {
	Name string `json:"name"`
	Sim  string `json:"sim"`
}

// Оператор % оставляет только то, что выше порога схожести (0.3) — готовый
// «возможно, вы имели в виду». На опечатку 'capucino' проходит лишь 'Cappuccino'.
func (q *Queries) DidYouMean(ctx context.Context) ([]DidYouMeanRow, error) {
	rows, err := q.db.Query(ctx, didYouMean)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DidYouMeanRow{}
	for rows.Next() {
		var i DidYouMeanRow
		if err := rows.Scan(&i.Name, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const similarityScores = `-- name: SimilarityScores :many

SELECT name, round(similarity(name, 'capucino')::numeric, 3)::text AS sim
FROM menu_search_lab
ORDER BY similarity(name, 'capucino') DESC, id
`

type SimilarityScoresRow struct {
	Name string `json:"name"`
	Sim  string `json:"sim"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — нечёткий поиск pg_trgm. similarity(a, b) меряет, насколько похожи строки
// по общим триграммам (0..1); оператор % истинен, когда схожесть выше порога
// pg_trgm.similarity_threshold (по умолчанию 0.3). Это ловит ОПЕЧАТКИ — то, чего
// ни LIKE, ни полнотекстовый поиск (07-05) не умеют. Запрос здесь — 'capucino'
// (опечатка в 'Cappuccino': пропущены p и c).
// similarity к каждому пункту меню, по убыванию. У 'Cappuccino' схожесть высокая,
// у остальных — почти ноль: триграммы 'capucino' совпадают в основном с ним.
// round(...)::text — стабильное печатаемое число (округляем real до 3 знаков).
func (q *Queries) SimilarityScores(ctx context.Context) ([]SimilarityScoresRow, error) {
	rows, err := q.db.Query(ctx, similarityScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimilarityScoresRow{}
	for rows.Next() {
		var i SimilarityScoresRow
		if err := rows.Scan(&i.Name, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
