// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — четыре оператора доступа к jsonb: -> (достать как jsonb), ->> (достать
	// как text), #>> (достать по пути как text) и @> (containment, «содержит»),
	// плюс ? (есть ли ключ). Это рабочая лошадка любого приложения, кладущего в БД
	// полуструктурированные данные. Containment @> ускоряет GIN-индекс (см. 06-05).
	// Доступ к полям. Ключевой контраст: -> оставляет значение как jsonb (молоко
	// приедет в кавычках: "oat"), а ->> отдаёт чистый text (oat). #>> идёт по пути:
	// '{extras,0}' — нулевой элемент массива extras. coalesce подменяет отсутствующее
	// значение на '∅' (у Егора нет ключа milk, у Бориса — массива extras) и заодно
	// даёт sqlc конкретный тип string вместо nullable interface{}.
	AccessOps(ctx context.Context) ([]AccessOpsRow, error)
	// Оператор ? — «есть ли ключ верхнего уровня». Находим заказы, где вообще
	// указали extras (даже пустой массив у Дины — ключ-то есть). Ср. с @>: ? про
	// НАЛИЧИЕ ключа, @> — про наличие пары ключ-значение.
	HasExtrasKey(ctx context.Context) ([]string, error)
	// Containment умеет заглядывать и в массивы: '{"extras":["honey"]}' матчит строки,
	// где массив extras содержит элемент honey. Глубокая структура — один оператор.
	HoneyInExtras(ctx context.Context) ([]string, error)
	// Containment @>: строка слева «содержит» json справа. '{"milk":"oat"}' матчит
	// любую строку, где есть ключ milk со значением oat — независимо от прочих полей.
	// Это НЕ равенство всего документа, а «есть ли в нём такая пара».
	OatMilkOrders(ctx context.Context) ([]OatMilkOrdersRow, error)
}

var _ Querier = (*Queries)(nil)
