// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const accessOps = `-- name: AccessOps :many

SELECT
    customer,
    coalesce((options -> 'milk')::text, '∅')   AS milk_jsonb,
    coalesce(options ->> 'milk', '∅')           AS milk_text,
    coalesce(options ->> 'size', '∅')           AS size,
    coalesce(options ->> 'shots', '∅')          AS shots,
    coalesce(options #>> '{extras,0}', '∅')     AS first_extra
FROM order_options_lab
ORDER BY id
`

type AccessOpsRow struct {
	Customer   string      `json:"customer"`
	MilkJsonb  interface{} `json:"milk_jsonb"`
	MilkText   interface{} `json:"milk_text"`
	Size       interface{} `json:"size"`
	Shots      interface{} `json:"shots"`
	FirstExtra interface{} `json:"first_extra"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — четыре оператора доступа к jsonb: -> (достать как jsonb), ->> (достать
// как text), #>> (достать по пути как text) и @> (containment, «содержит»),
// плюс ? (есть ли ключ). Это рабочая лошадка любого приложения, кладущего в БД
// полуструктурированные данные. Containment @> ускоряет GIN-индекс (см. 06-05).
// Доступ к полям. Ключевой контраст: -> оставляет значение как jsonb (молоко
// приедет в кавычках: "oat"), а ->> отдаёт чистый text (oat). #>> идёт по пути:
// '{extras,0}' — нулевой элемент массива extras. coalesce подменяет отсутствующее
// значение на '∅' (у Егора нет ключа milk, у Бориса — массива extras) и заодно
// даёт sqlc конкретный тип string вместо nullable interface{}.
func (q *Queries) AccessOps(ctx context.Context) ([]AccessOpsRow, error) {
	rows, err := q.db.Query(ctx, accessOps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessOpsRow{}
	for rows.Next() {
		var i AccessOpsRow
		if err := rows.Scan(
			&i.Customer,
			&i.MilkJsonb,
			&i.MilkText,
			&i.Size,
			&i.Shots,
			&i.FirstExtra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasExtrasKey = `-- name: HasExtrasKey :many
SELECT customer
FROM order_options_lab
WHERE options ? 'extras'
ORDER BY id
`

// Оператор ? — «есть ли ключ верхнего уровня». Находим заказы, где вообще
// указали extras (даже пустой массив у Дины — ключ-то есть). Ср. с @>: ? про
// НАЛИЧИЕ ключа, @> — про наличие пары ключ-значение.
func (q *Queries) HasExtrasKey(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, hasExtrasKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var customer string
		if err := rows.Scan(&customer); err != nil {
			return nil, err
		}
		items = append(items, customer)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const honeyInExtras = `-- name: HoneyInExtras :many
SELECT customer
FROM order_options_lab
WHERE options @> '{"extras":["honey"]}'
ORDER BY id
`

// Containment умеет заглядывать и в массивы: '{"extras":["honey"]}' матчит строки,
// где массив extras содержит элемент honey. Глубокая структура — один оператор.
func (q *Queries) HoneyInExtras(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, honeyInExtras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var customer string
		if err := rows.Scan(&customer); err != nil {
			return nil, err
		}
		items = append(items, customer)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oatMilkOrders = `-- name: OatMilkOrders :many
SELECT customer, options ->> 'size' AS size
FROM order_options_lab
WHERE options @> '{"milk":"oat"}'
ORDER BY id
`

type OatMilkOrdersRow struct {
	Customer string      `json:"customer"`
	Size     interface{} `json:"size"`
}

// Containment @>: строка слева «содержит» json справа. '{"milk":"oat"}' матчит
// любую строку, где есть ключ milk со значением oat — независимо от прочих полей.
// Это НЕ равенство всего документа, а «есть ли в нём такая пара».
func (q *Queries) OatMilkOrders(ctx context.Context) ([]OatMilkOrdersRow, error) {
	rows, err := q.db.Query(ctx, oatMilkOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OatMilkOrdersRow{}
	for rows.Next() {
		var i OatMilkOrdersRow
		if err := rows.Scan(&i.Customer, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
