// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const cubeAllAngles = `-- name: CubeAllAngles :many
SELECT
    coalesce(shop, '— все —')                  AS shop,
    coalesce(category, '— все —')              AS category,
    (sum(cents))::bigint                       AS cents,
    (grouping(shop) + grouping(category))::int AS level
FROM sales_fact_lab
GROUP BY CUBE (shop, category)
ORDER BY grouping(shop), shop, grouping(category), category
`

type CubeAllAnglesRow struct {
	Shop     string `json:"shop"`
	Category string `json:"category"`
	Cents    int64  `json:"cents"`
	Level    int32  `json:"level"`
}

// CUBE (shop, category): к строкам ROLLUP добавляются ещё подытоги по КАТЕГОРИИ
// поперёк магазинов (shop свёрнут, category — нет): «сколько всего coffee по
// всей сети». То есть все 4 комбинации свёрнутости двух колонок.
func (q *Queries) CubeAllAngles(ctx context.Context) ([]CubeAllAnglesRow, error) {
	rows, err := q.db.Query(ctx, cubeAllAngles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CubeAllAnglesRow{}
	for rows.Next() {
		var i CubeAllAnglesRow
		if err := rows.Scan(
			&i.Shop,
			&i.Category,
			&i.Cents,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupingSetsExplicit = `-- name: GroupingSetsExplicit :many
SELECT
    coalesce(shop, '— все —')                  AS shop,
    coalesce(category, '— все —')              AS category,
    (sum(cents))::bigint                       AS cents,
    (grouping(shop) + grouping(category))::int AS level
FROM sales_fact_lab
GROUP BY GROUPING SETS ((shop), (category), ())
ORDER BY grouping(shop), shop, grouping(category), category
`

type GroupingSetsExplicitRow struct {
	Shop     string `json:"shop"`
	Category string `json:"category"`
	Cents    int64  `json:"cents"`
	Level    int32  `json:"level"`
}

// GROUPING SETS перечисляет нужные срезы вручную: «итоги по магазину», «итоги по
// категории» и «общий итог» — без листьев (shop, category). Это даёт ровно три
// среза, которые в дашборде и нужны, без лишних строк CUBE.
func (q *Queries) GroupingSetsExplicit(ctx context.Context) ([]GroupingSetsExplicitRow, error) {
	rows, err := q.db.Query(ctx, groupingSetsExplicit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupingSetsExplicitRow{}
	for rows.Next() {
		var i GroupingSetsExplicitRow
		if err := rows.Scan(
			&i.Shop,
			&i.Category,
			&i.Cents,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupByShop = `-- name: RollupByShop :many

SELECT
    coalesce(shop, '— все —')                  AS shop,
    coalesce(category, '— все —')              AS category,
    (sum(cents))::bigint                       AS cents,
    (grouping(shop) + grouping(category))::int AS level
FROM sales_fact_lab
GROUP BY ROLLUP (shop, category)
ORDER BY grouping(shop), shop, grouping(category), category
`

type RollupByShopRow struct {
	Shop     string `json:"shop"`
	Category string `json:"category"`
	Cents    int64  `json:"cents"`
	Level    int32  `json:"level"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — субитоги одним запросом. Обычный GROUP BY (shop, category) даёт только
// листья. ROLLUP добавляет иерархические подытоги (по магазину + общий), CUBE —
// ВСЕ комбинации (ещё и по категории поперёк магазинов), GROUPING SETS — ровно
// те срезы, что перечислишь. Функция grouping(col) = 1, если в этой строке
// колонка «свёрнута» (NULL-подытог), и 0, если это реальное значение — так
// отличают строку-итог от настоящего NULL и сортируют итоги в конец.
// ROLLUP (shop, category): листья (shop, category) + подытог по каждому магазину
// (category свёрнута) + общий итог (обе свёрнуты). coalesce(...,'— все —')
// подписывает свёрнутые уровни; level = grouping(shop)+grouping(category)
// (0 — данные, 1 — подытог по магазину, 2 — общий итог).
func (q *Queries) RollupByShop(ctx context.Context) ([]RollupByShopRow, error) {
	rows, err := q.db.Query(ctx, rollupByShop)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RollupByShopRow{}
	for rows.Next() {
		var i RollupByShopRow
		if err := rows.Scan(
			&i.Shop,
			&i.Category,
			&i.Cents,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
