// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// CUBE (shop, category): к строкам ROLLUP добавляются ещё подытоги по КАТЕГОРИИ
	// поперёк магазинов (shop свёрнут, category — нет): «сколько всего coffee по
	// всей сети». То есть все 4 комбинации свёрнутости двух колонок.
	CubeAllAngles(ctx context.Context) ([]CubeAllAnglesRow, error)
	// GROUPING SETS перечисляет нужные срезы вручную: «итоги по магазину», «итоги по
	// категории» и «общий итог» — без листьев (shop, category). Это даёт ровно три
	// среза, которые в дашборде и нужны, без лишних строк CUBE.
	GroupingSetsExplicit(ctx context.Context) ([]GroupingSetsExplicitRow, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — субитоги одним запросом. Обычный GROUP BY (shop, category) даёт только
	// листья. ROLLUP добавляет иерархические подытоги (по магазину + общий), CUBE —
	// ВСЕ комбинации (ещё и по категории поперёк магазинов), GROUPING SETS — ровно
	// те срезы, что перечислишь. Функция grouping(col) = 1, если в этой строке
	// колонка «свёрнута» (NULL-подытог), и 0, если это реальное значение — так
	// отличают строку-итог от настоящего NULL и сортируют итоги в конец.
	// ROLLUP (shop, category): листья (shop, category) + подытог по каждому магазину
	// (category свёрнута) + общий итог (обе свёрнуты). coalesce(...,'— все —')
	// подписывает свёрнутые уровни; level = grouping(shop)+grouping(category)
	// (0 — данные, 1 — подытог по магазину, 2 — общий итог).
	RollupByShop(ctx context.Context) ([]RollupByShopRow, error)
}

var _ Querier = (*Queries)(nil)
