// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const articlesTaggedCoffee = `-- name: ArticlesTaggedCoffee :many
SELECT id, title
FROM articles
WHERE string_to_array(tags, ',') @> ARRAY['coffee']
ORDER BY id
`

type ArticlesTaggedCoffeeRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

// Оператор @> — «массив содержит». Находим статьи, у которых среди тегов есть
// 'coffee'. На больших объёмах такой поиск ускоряет GIN-индекс (модуль 06/07).
func (q *Queries) ArticlesTaggedCoffee(ctx context.Context) ([]ArticlesTaggedCoffeeRow, error) {
	rows, err := q.db.Query(ctx, articlesTaggedCoffee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticlesTaggedCoffeeRow{}
	for rows.Next() {
		var i ArticlesTaggedCoffeeRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enumOrder = `-- name: EnumOrder :one

SELECT
    ('small'::drink_size < 'large'::drink_size)  AS small_lt_large,
    ('large'::drink_size < 'small'::drink_size)  AS large_lt_small
`

type EnumOrderRow struct {
	SmallLtLarge bool `json:"small_lt_large"`
	LargeLtSmall bool `json:"large_lt_small"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — три «контейнерных» типа: enum (упорядочен по объявлению), массивы
// (text[] с операторами @> / = ANY) и jsonb (полуструктурированные данные). Это
// ВВЕДЕНИЕ: глубокий разбор jsonb, GIN-индексов и полнотекстового поиска — в
// модуле 07; здесь только знакомство и когда какой контейнер уместен.
// enum сравнивается и сортируется по порядку ОБЪЯВЛЕНИЯ значений
// (small < medium < large), а НЕ по алфавиту (иначе было бы large < medium <
// small). Это и есть смысл enum: упорядоченный конечный набор.
func (q *Queries) EnumOrder(ctx context.Context) (EnumOrderRow, error) {
	row := q.db.QueryRow(ctx, enumOrder)
	var i EnumOrderRow
	err := row.Scan(&i.SmallLtLarge, &i.LargeLtSmall)
	return i, err
}

const jSONBIntro = `-- name: JSONBIntro :one
SELECT
    coalesce('{"size":"L","milk":"oat","shots":2}'::jsonb ->> 'milk', '')        AS milk_text,
    coalesce(('{"size":"L","milk":"oat","shots":2}'::jsonb -> 'milk')::text, '') AS milk_json,
    coalesce('{"size":"L","milk":"oat","shots":2}'::jsonb ->> 'shots', '')       AS shots_text,
    jsonb_exists('{"size":"L","milk":"oat","shots":2}'::jsonb, 'milk')           AS has_milk
`

type JSONBIntroRow struct {
	MilkText  interface{} `json:"milk_text"`
	MilkJson  interface{} `json:"milk_json"`
	ShotsText interface{} `json:"shots_text"`
	HasMilk   bool        `json:"has_milk"`
}

// jsonb-литерал и базовые операторы. Ключевой контраст: ->> достаёт значение
// как text ('oat'), а -> оставляет его jsonb ('"oat"' — со скобками-кавычками).
// jsonb_exists (оператор ?) проверяет наличие ключа. coalesce → тип в Go = string.
func (q *Queries) JSONBIntro(ctx context.Context) (JSONBIntroRow, error) {
	row := q.db.QueryRow(ctx, jSONBIntro)
	var i JSONBIntroRow
	err := row.Scan(
		&i.MilkText,
		&i.MilkJson,
		&i.ShotsText,
		&i.HasMilk,
	)
	return i, err
}

const tagsAsArray = `-- name: TagsAsArray :many
SELECT id, title, string_to_array(tags, ',')::text[] AS tag_list
FROM articles
ORDER BY id
`

type TagsAsArrayRow struct {
	ID      int64    `json:"id"`
	Title   string   `json:"title"`
	TagList []string `json:"tag_list"`
}

// В каноне tags хранится строкой 'coffee,basics' (байт-совместимость с kafka-
// cookbook). string_to_array разворачивает её в text[] — в Go это []string
// (явный ::text[] подсказывает sqlc конкретный тип элемента).
func (q *Queries) TagsAsArray(ctx context.Context) ([]TagsAsArrayRow, error) {
	rows, err := q.db.Query(ctx, tagsAsArray)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagsAsArrayRow{}
	for rows.Next() {
		var i TagsAsArrayRow
		if err := rows.Scan(&i.ID, &i.Title, &i.TagList); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
