// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Оператор @> — «массив содержит». Находим статьи, у которых среди тегов есть
	// 'coffee'. На больших объёмах такой поиск ускоряет GIN-индекс (модуль 06/07).
	ArticlesTaggedCoffee(ctx context.Context) ([]ArticlesTaggedCoffeeRow, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — три «контейнерных» типа: enum (упорядочен по объявлению), массивы
	// (text[] с операторами @> / = ANY) и jsonb (полуструктурированные данные). Это
	// ВВЕДЕНИЕ: глубокий разбор jsonb, GIN-индексов и полнотекстового поиска — в
	// модуле 07; здесь только знакомство и когда какой контейнер уместен.
	// enum сравнивается и сортируется по порядку ОБЪЯВЛЕНИЯ значений
	// (small < medium < large), а НЕ по алфавиту (иначе было бы large < medium <
	// small). Это и есть смысл enum: упорядоченный конечный набор.
	EnumOrder(ctx context.Context) (EnumOrderRow, error)
	// jsonb-литерал и базовые операторы. Ключевой контраст: ->> достаёт значение
	// как text ('oat'), а -> оставляет его jsonb ('"oat"' — со скобками-кавычками).
	// jsonb_exists (оператор ?) проверяет наличие ключа. coalesce → тип в Go = string.
	JSONBIntro(ctx context.Context) (JSONBIntroRow, error)
	// В каноне tags хранится строкой 'coffee,basics' (байт-совместимость с kafka-
	// cookbook). string_to_array разворачивает её в text[] — в Go это []string
	// (явный ::text[] подсказывает sqlc конкретный тип элемента).
	TagsAsArray(ctx context.Context) ([]TagsAsArrayRow, error)
}

var _ Querier = (*Queries)(nil)
