// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	InsertNatural(ctx context.Context, arg InsertNaturalParams) error
	// NULL в PK-колонку code: PRIMARY KEY навязал NOT NULL → SQLSTATE 23502.
	InsertNaturalNullCode(ctx context.Context, name string) error
	// NULL в обычную NOT NULL колонку name → SQLSTATE 23502.
	InsertNaturalNullName(ctx context.Context, code string) error
	InsertSurrogate(ctx context.Context, arg InsertSurrogateParams) (int64, error)
	NaturalCodeExists(ctx context.Context, code string) (bool, error)
	// Переименование натурального ключа = смена самого значения PK.
	RenameNaturalCode(ctx context.Context, arg RenameNaturalCodeParams) error
	// Переименование атрибута code; id (identity строки) не трогаем.
	RenameSurrogateCode(ctx context.Context, arg RenameSurrogateCodeParams) error
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — PRIMARY KEY (= NOT NULL + UNIQUE) и выбор ключа. Показываем, что PK
	// отвергает и NULL, и дубль, что NOT NULL ловит пустую обязательную колонку, и
	// ключевой контраст: при переименовании бизнес-кода натуральный ключ «уезжает»,
	// а суррогатный id остаётся.
	ResetNatural(ctx context.Context) error
	ResetSurrogate(ctx context.Context) error
	SurrogateIDByCode(ctx context.Context, code string) (int64, error)
}

var _ Querier = (*Queries)(nil)
