// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const insertNatural = `-- name: InsertNatural :exec
INSERT INTO shop_natural (code, name) VALUES ($1, $2)
`

type InsertNaturalParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) InsertNatural(ctx context.Context, arg InsertNaturalParams) error {
	_, err := q.db.Exec(ctx, insertNatural, arg.Code, arg.Name)
	return err
}

const insertNaturalNullCode = `-- name: InsertNaturalNullCode :exec
INSERT INTO shop_natural (code, name) VALUES (NULL, $1)
`

// NULL в PK-колонку code: PRIMARY KEY навязал NOT NULL → SQLSTATE 23502.
func (q *Queries) InsertNaturalNullCode(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertNaturalNullCode, name)
	return err
}

const insertNaturalNullName = `-- name: InsertNaturalNullName :exec
INSERT INTO shop_natural (code, name) VALUES ($1, NULL)
`

// NULL в обычную NOT NULL колонку name → SQLSTATE 23502.
func (q *Queries) InsertNaturalNullName(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, insertNaturalNullName, code)
	return err
}

const insertSurrogate = `-- name: InsertSurrogate :one
INSERT INTO shop_surrogate (code, name) VALUES ($1, $2)
RETURNING id
`

type InsertSurrogateParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) InsertSurrogate(ctx context.Context, arg InsertSurrogateParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSurrogate, arg.Code, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const naturalCodeExists = `-- name: NaturalCodeExists :one
SELECT EXISTS (SELECT 1 FROM shop_natural WHERE code = $1)::boolean AS present
`

func (q *Queries) NaturalCodeExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, naturalCodeExists, code)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const renameNaturalCode = `-- name: RenameNaturalCode :exec
UPDATE shop_natural SET code = $2 WHERE code = $1
`

type RenameNaturalCodeParams struct {
	Code   string `json:"code"`
	Code_2 string `json:"code_2"`
}

// Переименование натурального ключа = смена самого значения PK.
func (q *Queries) RenameNaturalCode(ctx context.Context, arg RenameNaturalCodeParams) error {
	_, err := q.db.Exec(ctx, renameNaturalCode, arg.Code, arg.Code_2)
	return err
}

const renameSurrogateCode = `-- name: RenameSurrogateCode :exec
UPDATE shop_surrogate SET code = $2 WHERE code = $1
`

type RenameSurrogateCodeParams struct {
	Code   string `json:"code"`
	Code_2 string `json:"code_2"`
}

// Переименование атрибута code; id (identity строки) не трогаем.
func (q *Queries) RenameSurrogateCode(ctx context.Context, arg RenameSurrogateCodeParams) error {
	_, err := q.db.Exec(ctx, renameSurrogateCode, arg.Code, arg.Code_2)
	return err
}

const resetNatural = `-- name: ResetNatural :exec

TRUNCATE shop_natural
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — PRIMARY KEY (= NOT NULL + UNIQUE) и выбор ключа. Показываем, что PK
// отвергает и NULL, и дубль, что NOT NULL ловит пустую обязательную колонку, и
// ключевой контраст: при переименовании бизнес-кода натуральный ключ «уезжает»,
// а суррогатный id остаётся.
func (q *Queries) ResetNatural(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetNatural)
	return err
}

const resetSurrogate = `-- name: ResetSurrogate :exec
TRUNCATE shop_surrogate RESTART IDENTITY
`

func (q *Queries) ResetSurrogate(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetSurrogate)
	return err
}

const surrogateIDByCode = `-- name: SurrogateIDByCode :one
SELECT id FROM shop_surrogate WHERE code = $1
`

func (q *Queries) SurrogateIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, surrogateIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}
