// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Author      string             `json:"author"`
	Tags        string             `json:"tags"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID        int64              `json:"id"`
	Phone     string             `json:"phone"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Drink struct {
	ID          int64              `json:"id"`
	Sku         string             `json:"sku"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	BasePrice   int64              `json:"base_price"`
	Stock       int32              `json:"stock"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Inventory struct {
	ShopID    int64              `json:"shop_id"`
	DrinkID   int64              `json:"drink_id"`
	OnHand    int32              `json:"on_hand"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID         int64              `json:"id"`
	CustomerID string             `json:"customer_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	ID        int64              `json:"id"`
	OrderID   int64              `json:"order_id"`
	DrinkID   int64              `json:"drink_id"`
	Quantity  int32              `json:"quantity"`
	UnitPrice int64              `json:"unit_price"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID          int64              `json:"id"`
	AggregateID string             `json:"aggregate_id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type ProcessedOutboxID struct {
	OutboxID    int64              `json:"outbox_id"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Shop struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	City      string             `json:"city"`
	OpenedOn  pgtype.Date        `json:"opened_on"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StockLevel struct {
	ShopCode string `json:"shop_code"`
	DrinkSku string `json:"drink_sku"`
	OnHand   int32  `json:"on_hand"`
}
