// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const listStock = `-- name: ListStock :many
SELECT shop_code, drink_sku, on_hand FROM stock_levels
ORDER BY shop_code, drink_sku
`

func (q *Queries) ListStock(ctx context.Context) ([]StockLevel, error) {
	rows, err := q.db.Query(ctx, listStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockLevel{}
	for rows.Next() {
		var i StockLevel
		if err := rows.Scan(&i.ShopCode, &i.DrinkSku, &i.OnHand); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateStock = `-- name: TruncateStock :exec

TRUNCATE stock_levels
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — upsert: «вставь, а если такой ключ уже есть — обнови». INSERT ... ON
// CONFLICT (...) DO UPDATE делает это одной атомарной командой, безопасной под
// конкуренцией. EXCLUDED — псевдотаблица с той строкой, которую мы пытались
// вставить (новые значения). Альтернатива DO NOTHING тихо проглатывает дубль.
// Обнуляем таблицу перед демо — вывод воспроизводим.
func (q *Queries) TruncateStock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateStock)
	return err
}

const upsertIgnore = `-- name: UpsertIgnore :execrows
INSERT INTO stock_levels (shop_code, drink_sku, on_hand)
VALUES ($1, $2, $3)
ON CONFLICT (shop_code, drink_sku) DO NOTHING
`

type UpsertIgnoreParams struct {
	ShopCode string `json:"shop_code"`
	DrinkSku string `json:"drink_sku"`
	OnHand   int32  `json:"on_hand"`
}

// ON CONFLICT DO NOTHING: при конфликте строка не меняется и не вставляется.
// :execrows вернёт 1 (вставили) или 0 (конфликт проигнорирован) — это идиома
// идемпотентной вставки (ср. processed_outbox_ids в каноне: дубли проглатываются).
func (q *Queries) UpsertIgnore(ctx context.Context, arg UpsertIgnoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertIgnore, arg.ShopCode, arg.DrinkSku, arg.OnHand)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStock = `-- name: UpsertStock :one
INSERT INTO stock_levels (shop_code, drink_sku, on_hand)
VALUES ($1, $2, $3)
ON CONFLICT (shop_code, drink_sku)
DO UPDATE SET on_hand = EXCLUDED.on_hand
RETURNING shop_code, drink_sku, on_hand, (xmax <> 0) AS was_update
`

type UpsertStockParams struct {
	ShopCode string `json:"shop_code"`
	DrinkSku string `json:"drink_sku"`
	OnHand   int32  `json:"on_hand"`
}

type UpsertStockRow struct {
	ShopCode  string `json:"shop_code"`
	DrinkSku  string `json:"drink_sku"`
	OnHand    int32  `json:"on_hand"`
	WasUpdate bool   `json:"was_update"`
}

// «Вставь или обнови»: при конфликте по (shop_code, drink_sku) переписываем
// on_hand значением из EXCLUDED (то, что пытались вставить). RETURNING отдаёт
// итоговую строку; (xmax <> 0) — известный приём отличить вставку от
// обновления: у только что вставленной строки xmax = 0, у обновлённой — нет.
func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) (UpsertStockRow, error) {
	row := q.db.QueryRow(ctx, upsertStock, arg.ShopCode, arg.DrinkSku, arg.OnHand)
	var i UpsertStockRow
	err := row.Scan(
		&i.ShopCode,
		&i.DrinkSku,
		&i.OnHand,
		&i.WasUpdate,
	)
	return i, err
}
