// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	ListStock(ctx context.Context) ([]StockLevel, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — upsert: «вставь, а если такой ключ уже есть — обнови». INSERT ... ON
	// CONFLICT (...) DO UPDATE делает это одной атомарной командой, безопасной под
	// конкуренцией. EXCLUDED — псевдотаблица с той строкой, которую мы пытались
	// вставить (новые значения). Альтернатива DO NOTHING тихо проглатывает дубль.
	// Обнуляем таблицу перед демо — вывод воспроизводим.
	TruncateStock(ctx context.Context) error
	// ON CONFLICT DO NOTHING: при конфликте строка не меняется и не вставляется.
	// :execrows вернёт 1 (вставили) или 0 (конфликт проигнорирован) — это идиома
	// идемпотентной вставки (ср. processed_outbox_ids в каноне: дубли проглатываются).
	UpsertIgnore(ctx context.Context, arg UpsertIgnoreParams) (int64, error)
	// «Вставь или обнови»: при конфликте по (shop_code, drink_sku) переписываем
	// on_hand значением из EXCLUDED (то, что пытались вставить). RETURNING отдаёт
	// итоговую строку; (xmax <> 0) — известный приём отличить вставку от
	// обновления: у только что вставленной строки xmax = 0, у обновлённой — нет.
	UpsertStock(ctx context.Context, arg UpsertStockParams) (UpsertStockRow, error)
}

var _ Querier = (*Queries)(nil)
