// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Запрос relay'я. Берёт пачку неопубликованных событий ПОД блокировкой строк с
	// SKIP LOCKED (как очередь из 09-02) — чтобы несколько relay-воркеров могли
	// работать параллельно, не доставляя одно событие дважды и не блокируя друг
	// друга. Идёт по partial-индексу outbox_unpublished_idx (WHERE published_at IS NULL).
	ClaimUnpublished(ctx context.Context, limit int32) ([]ClaimUnpublishedRow, error)
	// Сколько заказов сейчас в таблице — для проверки атомарности (откат тянет за
	// собой и заказ, и событие).
	CountOrders(ctx context.Context) (int64, error)
	// Сколько событий ещё ждут доставки — для наглядности в демо.
	CountUnpublished(ctx context.Context) (int64, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — transactional outbox. Проблема, которую он решает: надо записать
	// бизнес-факт (заказ) И событие о нём (для рассылки/CDC) так, чтобы они либо
	// появились ВМЕСТЕ, либо никак. Если писать заказ в БД, а событие — отдельно в
	// брокер, между двумя записями возможен сбой: заказ есть, события нет (или
	// наоборот). Outbox убирает зазор: заказ и строку-событие пишем в ОДНОЙ
	// транзакции в одну базу — атомарность даёт сам Postgres. Отдельный процесс
	// (relay) потом вычитывает неопубликованные события и доставляет их.
	// Бизнес-факт. customer_id здесь TEXT (так в каноне), amount приходит строкой и
	// кастуется в numeric. Именованные параметры (@amount) дают аккуратное имя поля
	// в сгенерированной структуре. Вызывается ВНУТРИ транзакции вместе с InsertOutbox.
	InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error)
	// Событие об этом факте — в той же транзакции, что и заказ. aggregate_id
	// связывает событие с заказом, topic — куда его потом доставить, payload —
	// тело события (jsonb). published_at остаётся NULL: «ещё не доставлено».
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) (int64, error)
	// relay доставил событие → помечаем опубликованным. Делается в той же
	// транзакции, что и ClaimUnpublished: доставили и отметили атомарно.
	MarkPublished(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
