// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimUnpublished = `-- name: ClaimUnpublished :many
SELECT id, aggregate_id, topic, payload
FROM outbox
WHERE published_at IS NULL
ORDER BY id
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type ClaimUnpublishedRow struct {
	ID          int64  `json:"id"`
	AggregateID string `json:"aggregate_id"`
	Topic       string `json:"topic"`
	Payload     []byte `json:"payload"`
}

// Запрос relay'я. Берёт пачку неопубликованных событий ПОД блокировкой строк с
// SKIP LOCKED (как очередь из 09-02) — чтобы несколько relay-воркеров могли
// работать параллельно, не доставляя одно событие дважды и не блокируя друг
// друга. Идёт по partial-индексу outbox_unpublished_idx (WHERE published_at IS NULL).
func (q *Queries) ClaimUnpublished(ctx context.Context, limit int32) ([]ClaimUnpublishedRow, error) {
	rows, err := q.db.Query(ctx, claimUnpublished, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimUnpublishedRow{}
	for rows.Next() {
		var i ClaimUnpublishedRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.Topic,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOrders = `-- name: CountOrders :one
SELECT count(*) FROM orders
`

// Сколько заказов сейчас в таблице — для проверки атомарности (откат тянет за
// собой и заказ, и событие).
func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnpublished = `-- name: CountUnpublished :one
SELECT count(*) FROM outbox WHERE published_at IS NULL
`

// Сколько событий ещё ждут доставки — для наглядности в демо.
func (q *Queries) CountUnpublished(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpublished)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertOrder = `-- name: InsertOrder :one

INSERT INTO orders (customer_id, amount, status)
VALUES ($1, $2::numeric, $3)
RETURNING id
`

type InsertOrderParams struct {
	CustomerID string         `json:"customer_id"`
	Amount     pgtype.Numeric `json:"amount"`
	Status     string         `json:"status"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — transactional outbox. Проблема, которую он решает: надо записать
// бизнес-факт (заказ) И событие о нём (для рассылки/CDC) так, чтобы они либо
// появились ВМЕСТЕ, либо никак. Если писать заказ в БД, а событие — отдельно в
// брокер, между двумя записями возможен сбой: заказ есть, события нет (или
// наоборот). Outbox убирает зазор: заказ и строку-событие пишем в ОДНОЙ
// транзакции в одну базу — атомарность даёт сам Postgres. Отдельный процесс
// (relay) потом вычитывает неопубликованные события и доставляет их.
// Бизнес-факт. customer_id здесь TEXT (так в каноне), amount приходит строкой и
// кастуется в numeric. Именованные параметры (@amount) дают аккуратное имя поля
// в сгенерированной структуре. Вызывается ВНУТРИ транзакции вместе с InsertOutbox.
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrder, arg.CustomerID, arg.Amount, arg.Status)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (aggregate_id, topic, payload)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertOutboxParams struct {
	AggregateID string `json:"aggregate_id"`
	Topic       string `json:"topic"`
	Payload     []byte `json:"payload"`
}

// Событие об этом факте — в той же транзакции, что и заказ. aggregate_id
// связывает событие с заказом, topic — куда его потом доставить, payload —
// тело события (jsonb). published_at остаётся NULL: «ещё не доставлено».
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOutbox, arg.AggregateID, arg.Topic, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markPublished = `-- name: MarkPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

// relay доставил событие → помечаем опубликованным. Делается в той же
// транзакции, что и ClaimUnpublished: доставили и отметили атомарно.
func (q *Queries) MarkPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPublished, id)
	return err
}
