// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Сборка в обратную сторону: из строк канона drinks собираем ОДИН jsonb-массив
	// объектов. jsonb_build_object лепит объект из пар, jsonb_agg(... ORDER BY id)
	// агрегирует строки в массив (ORDER BY внутри агрегата → стабильный порядок).
	BuildMenu(ctx context.Context) (interface{}, error)
	// Предикаты пути: @? («существует ли совпадение») и @@ («истинно ли условие»).
	// @? '$.ingredients[*] ? (@.name == "milk")' — есть ли ингредиент molk;
	// @@ '$.kcal > 100' — калорийный ли напиток. Оба возвращают boolean.
	PathPredicates(ctx context.Context) ([]PathPredicatesRow, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — SQL/JSON path (язык jsonpath: $.a.b, [*], фильтры ? (@.x > N)) и сборка
	// jsonb (jsonb_set, jsonb_build_object, jsonb_agg). jsonpath — стандартный
	// способ доставать данные из вложенных документов, куда обычные -> / #> лезут
	// неуклюже.
	//
	// Заметка по версиям: JSON_TABLE (развернуть jsonb в реляционную таблицу прямо
	// в FROM) появился в PG17, не в PG18 — здесь его НЕ используем; нужные нам
	// jsonb_path_* и сборочные функции есть с PG12.
	// jsonpath на рецепте Латте (id=1). $.ingredients[*].name — имена всех
	// ингредиентов; фильтр ? (@.grams > 100) оставляет только тяжёлые (по граммам);
	// jsonb_path_query_first берёт первое совпадение. _array собирает совпадения в
	// jsonb-массив, ::text делает его печатаемым. coalesce → конкретный тип string.
	PathQueries(ctx context.Context) (PathQueriesRow, error)
	// jsonb_set точечно правит поле и возвращает НОВЫЙ документ — хранимая строка не
	// меняется (это чистая функция, ср. write-amplification из 07-02: «правка» =
	// сборка нового значения). Показываем kcal до и после правки на 130.
	SetField(ctx context.Context) (SetFieldRow, error)
}

var _ Querier = (*Queries)(nil)
