// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const buildMenu = `-- name: BuildMenu :one
SELECT coalesce(
    jsonb_agg(jsonb_build_object('sku', sku, 'price_cents', base_price) ORDER BY id)::text,
    '[]'
) AS menu_json
FROM drinks
`

// Сборка в обратную сторону: из строк канона drinks собираем ОДИН jsonb-массив
// объектов. jsonb_build_object лепит объект из пар, jsonb_agg(... ORDER BY id)
// агрегирует строки в массив (ORDER BY внутри агрегата → стабильный порядок).
func (q *Queries) BuildMenu(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, buildMenu)
	var menu_json interface{}
	err := row.Scan(&menu_json)
	return menu_json, err
}

const pathPredicates = `-- name: PathPredicates :many
SELECT
    name,
    (recipe @? '$.ingredients[*] ? (@.name == "milk")') AS has_milk,
    (recipe @@ '$.kcal > 100')                          AS over_100_kcal
FROM drink_recipe_lab
ORDER BY id
`

type PathPredicatesRow struct {
	Name        string      `json:"name"`
	HasMilk     interface{} `json:"has_milk"`
	Over100Kcal interface{} `json:"over_100_kcal"`
}

// Предикаты пути: @? («существует ли совпадение») и @@ («истинно ли условие»).
// @? '$.ingredients[*] ? (@.name == "milk")' — есть ли ингредиент molk;
// @@ '$.kcal > 100' — калорийный ли напиток. Оба возвращают boolean.
func (q *Queries) PathPredicates(ctx context.Context) ([]PathPredicatesRow, error) {
	rows, err := q.db.Query(ctx, pathPredicates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PathPredicatesRow{}
	for rows.Next() {
		var i PathPredicatesRow
		if err := rows.Scan(&i.Name, &i.HasMilk, &i.Over100Kcal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pathQueries = `-- name: PathQueries :one

SELECT
    coalesce(jsonb_path_query_array(recipe, '$.ingredients[*].name')::text, '[]')                   AS all_names,
    coalesce(jsonb_path_query_array(recipe, '$.ingredients[*] ? (@.grams > 100).name')::text, '[]') AS heavy_names,
    coalesce(jsonb_path_query_first(recipe, '$.ingredients[0].name')::text, 'null')                 AS first_name
FROM drink_recipe_lab
WHERE id = 1
`

type PathQueriesRow struct {
	AllNames   interface{} `json:"all_names"`
	HeavyNames interface{} `json:"heavy_names"`
	FirstName  interface{} `json:"first_name"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — SQL/JSON path (язык jsonpath: $.a.b, [*], фильтры ? (@.x > N)) и сборка
// jsonb (jsonb_set, jsonb_build_object, jsonb_agg). jsonpath — стандартный
// способ доставать данные из вложенных документов, куда обычные -> / #> лезут
// неуклюже.
//
// Заметка по версиям: JSON_TABLE (развернуть jsonb в реляционную таблицу прямо
// в FROM) появился в PG17, не в PG18 — здесь его НЕ используем; нужные нам
// jsonb_path_* и сборочные функции есть с PG12.
// jsonpath на рецепте Латте (id=1). $.ingredients[*].name — имена всех
// ингредиентов; фильтр ? (@.grams > 100) оставляет только тяжёлые (по граммам);
// jsonb_path_query_first берёт первое совпадение. _array собирает совпадения в
// jsonb-массив, ::text делает его печатаемым. coalesce → конкретный тип string.
func (q *Queries) PathQueries(ctx context.Context) (PathQueriesRow, error) {
	row := q.db.QueryRow(ctx, pathQueries)
	var i PathQueriesRow
	err := row.Scan(&i.AllNames, &i.HeavyNames, &i.FirstName)
	return i, err
}

const setField = `-- name: SetField :one
SELECT
    recipe ->> 'kcal'                             AS kcal_before,
    jsonb_set(recipe, '{kcal}', '130') ->> 'kcal' AS kcal_after
FROM drink_recipe_lab
WHERE id = 1
`

type SetFieldRow struct {
	KcalBefore interface{} `json:"kcal_before"`
	KcalAfter  interface{} `json:"kcal_after"`
}

// jsonb_set точечно правит поле и возвращает НОВЫЙ документ — хранимая строка не
// меняется (это чистая функция, ср. write-amplification из 07-02: «правка» =
// сборка нового значения). Показываем kcal до и после правки на 130.
func (q *Queries) SetField(ctx context.Context) (SetFieldRow, error) {
	row := q.db.QueryRow(ctx, setField)
	var i SetFieldRow
	err := row.Scan(&i.KcalBefore, &i.KcalAfter)
	return i, err
}
