// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// count(*) считает строки; count(o.id) пропускает строки, где o.id = NULL —
	// клиент без заказов (Карина) в count(o.id) не попадёт.
	CountStarVsCol(ctx context.Context) (CountStarVsColRow, error)
	// LEFT JOIN порождает настоящие NULL: у клиента без заказов order_id = NULL.
	// sqlc видит, что колонка из LEFT JOIN nullable, и типизирует её как pgtype.Int8
	// (Valid=false для NULL) — типобезопасная работа с «отсутствием значения».
	CustomersWithOrders(ctx context.Context) ([]CustomersWithOrdersRow, error)
	// boolean прямо из выражения: предикат base_price > 400 → bool (в Go — bool).
	MenuPremiumFlag(ctx context.Context) ([]MenuPremiumFlagRow, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — три «скучных» типа, на которых ломаются приложения: text (держим его,
	// а не char(n) с паддингом), boolean (трёхзначная логика) и NULL. NULL — не
	// значение, а «неизвестно»: сравнение с ним даёт NULL, а не true/false. Полный
	// разбор NULL — в 03-06; здесь только тизер, чтобы ловушка не застала врасплох.
	// Почему нельзя писать WHERE col = NULL: сравнение с NULL даёт не FALSE, а NULL
	// («неизвестно»). Здесь это видно так: (NULL = NULL) — это не TRUE и это NULL.
	// Правильная проверка на отсутствие значения — IS NULL / IS NOT NULL.
	NullComparison(ctx context.Context) (NullComparisonRow, error)
	// text сравнивается по байтам — хвостовой пробел значим ('abc' ≠ 'abc ').
	// char(n) дополняет до длины пробелами, и при сравнении они «съедаются»
	// ('abc' == 'abc  '). Поэтому в курсе мы держим text, а не char(n).
	TextEquality(ctx context.Context) (TextEqualityRow, error)
}

var _ Querier = (*Queries)(nil)
