// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStarVsCol = `-- name: CountStarVsCol :one
SELECT
    count(*)     AS rows_total,
    count(o.id)  AS rows_with_order
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id::text
`

type CountStarVsColRow struct {
	RowsTotal     int64 `json:"rows_total"`
	RowsWithOrder int64 `json:"rows_with_order"`
}

// count(*) считает строки; count(o.id) пропускает строки, где o.id = NULL —
// клиент без заказов (Карина) в count(o.id) не попадёт.
func (q *Queries) CountStarVsCol(ctx context.Context) (CountStarVsColRow, error) {
	row := q.db.QueryRow(ctx, countStarVsCol)
	var i CountStarVsColRow
	err := row.Scan(&i.RowsTotal, &i.RowsWithOrder)
	return i, err
}

const customersWithOrders = `-- name: CustomersWithOrders :many
SELECT c.id AS customer_id, c.name, o.id AS order_id
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id::text
ORDER BY c.id, o.id
`

type CustomersWithOrdersRow struct {
	CustomerID int64       `json:"customer_id"`
	Name       string      `json:"name"`
	OrderID    pgtype.Int8 `json:"order_id"`
}

// LEFT JOIN порождает настоящие NULL: у клиента без заказов order_id = NULL.
// sqlc видит, что колонка из LEFT JOIN nullable, и типизирует её как pgtype.Int8
// (Valid=false для NULL) — типобезопасная работа с «отсутствием значения».
func (q *Queries) CustomersWithOrders(ctx context.Context) ([]CustomersWithOrdersRow, error) {
	rows, err := q.db.Query(ctx, customersWithOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomersWithOrdersRow{}
	for rows.Next() {
		var i CustomersWithOrdersRow
		if err := rows.Scan(&i.CustomerID, &i.Name, &i.OrderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuPremiumFlag = `-- name: MenuPremiumFlag :many
SELECT id, name, (base_price > 400) AS is_premium
FROM drinks
ORDER BY id
`

type MenuPremiumFlagRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	IsPremium bool   `json:"is_premium"`
}

// boolean прямо из выражения: предикат base_price > 400 → bool (в Go — bool).
func (q *Queries) MenuPremiumFlag(ctx context.Context) ([]MenuPremiumFlagRow, error) {
	rows, err := q.db.Query(ctx, menuPremiumFlag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuPremiumFlagRow{}
	for rows.Next() {
		var i MenuPremiumFlagRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsPremium); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nullComparison = `-- name: NullComparison :one

SELECT
    ((NULL = NULL) IS NOT TRUE)::boolean  AS eq_null_is_not_true,
    ((NULL = NULL) IS NULL)::boolean      AS eq_null_is_unknown
`

type NullComparisonRow struct {
	EqNullIsNotTrue bool `json:"eq_null_is_not_true"`
	EqNullIsUnknown bool `json:"eq_null_is_unknown"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — три «скучных» типа, на которых ломаются приложения: text (держим его,
// а не char(n) с паддингом), boolean (трёхзначная логика) и NULL. NULL — не
// значение, а «неизвестно»: сравнение с ним даёт NULL, а не true/false. Полный
// разбор NULL — в 03-06; здесь только тизер, чтобы ловушка не застала врасплох.
// Почему нельзя писать WHERE col = NULL: сравнение с NULL даёт не FALSE, а NULL
// («неизвестно»). Здесь это видно так: (NULL = NULL) — это не TRUE и это NULL.
// Правильная проверка на отсутствие значения — IS NULL / IS NOT NULL.
func (q *Queries) NullComparison(ctx context.Context) (NullComparisonRow, error) {
	row := q.db.QueryRow(ctx, nullComparison)
	var i NullComparisonRow
	err := row.Scan(&i.EqNullIsNotTrue, &i.EqNullIsUnknown)
	return i, err
}

const textEquality = `-- name: TextEquality :one
SELECT
    ('abc' = 'abc ')                     AS text_trailing_space_eq,
    ('abc'::char(5) = 'abc  '::char(5))  AS char_padded_eq
`

type TextEqualityRow struct {
	TextTrailingSpaceEq bool `json:"text_trailing_space_eq"`
	CharPaddedEq        bool `json:"char_padded_eq"`
}

// text сравнивается по байтам — хвостовой пробел значим ('abc' ≠ 'abc ').
// char(n) дополняет до длины пробелами, и при сравнении они «съедаются»
// ('abc' == 'abc  '). Поэтому в курсе мы держим text, а не char(n).
func (q *Queries) TextEquality(ctx context.Context) (TextEqualityRow, error) {
	row := q.db.QueryRow(ctx, textEquality)
	var i TextEqualityRow
	err := row.Scan(&i.TextTrailingSpaceEq, &i.CharPaddedEq)
	return i, err
}
