// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const floatVsNumeric = `-- name: FloatVsNumeric :one

SELECT
    (0.1::float8 + 0.2::float8)::float8           AS float_sum,
    (0.1::numeric + 0.2::numeric)::text           AS numeric_sum,
    (0.1::float8 + 0.2::float8 = 0.3::float8)      AS float_eq_03,
    (0.1::numeric + 0.2::numeric = 0.3::numeric)  AS numeric_eq_03
`

type FloatVsNumericRow struct {
	FloatSum    float64 `json:"float_sum"`
	NumericSum  string  `json:"numeric_sum"`
	FloatEq03   bool    `json:"float_eq_03"`
	NumericEq03 bool    `json:"numeric_eq_03"`
}

// query.sql — протагонист урока. SQL пишем руками; `make gen` (sqlc generate)
// генерирует типизированный pgx-код в internal/db/. Имя после `-- name:` →
// метод на *db.Queries; суффикс (:one / :many) — форма результата.
//
// Тема урока — числа и деньги. Главный вывод: float для денег НЕ годится
// (0.1 + 0.2 ≠ 0.3), а в приложении деньги удобнее всего держать целыми в
// минорных единицах (центах) как BIGINT — точно и ложится в Go int64.
// Классическая ловушка: в double precision 0.1 + 0.2 не равно 0.3 (двоичное
// представление десятичных дробей неточно). В numeric — равно. float_sum
// остаётся float8 (в Go это float64 — увидишь «хвост»), numeric_sum приводим к
// text только ради аккуратной печати (в Go numeric — это pgtype.Numeric).
func (q *Queries) FloatVsNumeric(ctx context.Context) (FloatVsNumericRow, error) {
	row := q.db.QueryRow(ctx, floatVsNumeric)
	var i FloatVsNumericRow
	err := row.Scan(
		&i.FloatSum,
		&i.NumericSum,
		&i.FloatEq03,
		&i.NumericEq03,
	)
	return i, err
}

const menuPriced = `-- name: MenuPriced :many
SELECT id, name, base_price
FROM drinks
ORDER BY id
`

type MenuPricedRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	BasePrice int64  `json:"base_price"`
}

// Меню Brew. base_price — BIGINT в центах: целое число, без float-погрешностей.
// В рубли.копейки разворачиваем уже в приложении (base_price/100 и %100).
func (q *Queries) MenuPriced(ctx context.Context) ([]MenuPricedRow, error) {
	rows, err := q.db.Query(ctx, menuPriced)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuPricedRow{}
	for rows.Next() {
		var i MenuPricedRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BasePrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderTotalCents = `-- name: OrderTotalCents :one
SELECT coalesce(sum(quantity * unit_price), 0)::bigint AS total_cents
FROM order_items
WHERE order_id = $1
`

// Итог заказа целиком в центах: sum по позициям. COALESCE на случай пустого
// заказа, ::bigint — потому что sum() над bigint возвращает numeric.
func (q *Queries) OrderTotalCents(ctx context.Context, orderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, orderTotalCents, orderID)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}
