// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// query.sql — протагонист урока. SQL пишем руками; `make gen` (sqlc generate)
	// генерирует типизированный pgx-код в internal/db/. Имя после `-- name:` →
	// метод на *db.Queries; суффикс (:one / :many) — форма результата.
	//
	// Тема урока — числа и деньги. Главный вывод: float для денег НЕ годится
	// (0.1 + 0.2 ≠ 0.3), а в приложении деньги удобнее всего держать целыми в
	// минорных единицах (центах) как BIGINT — точно и ложится в Go int64.
	// Классическая ловушка: в double precision 0.1 + 0.2 не равно 0.3 (двоичное
	// представление десятичных дробей неточно). В numeric — равно. float_sum
	// остаётся float8 (в Go это float64 — увидишь «хвост»), numeric_sum приводим к
	// text только ради аккуратной печати (в Go numeric — это pgtype.Numeric).
	FloatVsNumeric(ctx context.Context) (FloatVsNumericRow, error)
	// Меню Brew. base_price — BIGINT в центах: целое число, без float-погрешностей.
	// В рубли.копейки разворачиваем уже в приложении (base_price/100 и %100).
	MenuPriced(ctx context.Context) ([]MenuPricedRow, error)
	// Итог заказа целиком в центах: sum по позициям. COALESCE на случай пустого
	// заказа, ::bigint — потому что sum() над bigint возвращает numeric.
	OrderTotalCents(ctx context.Context, orderID int64) (int64, error)
}

var _ Querier = (*Queries)(nil)
