// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const filterMenu = `-- name: FilterMenu :many

SELECT id, name, base_price
FROM drinks
WHERE category = $1
ORDER BY base_price
LIMIT $2
`

type FilterMenuParams struct {
	Category string `json:"category"`
	PageSize int32  `json:"page_size"`
}

type FilterMenuRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	BasePrice int64  `json:"base_price"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — как достать ровно нужные строки в нужном порядке и листать их
// постранично. WHERE/ORDER/LIMIT — основа; затем два способа пагинации: OFFSET
// (простой, но дорогой на глубоких страницах) и keyset (по «курсору» из
// последней строки — летит по индексу).
// WHERE/ORDER/LIMIT: отбираем категорию, сортируем по цене, берём не больше N.
// Полный порядок здесь не критичен (одна категория, печатаем как есть).
func (q *Queries) FilterMenu(ctx context.Context, arg FilterMenuParams) ([]FilterMenuRow, error) {
	rows, err := q.db.Query(ctx, filterMenu, arg.Category, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterMenuRow{}
	for rows.Next() {
		var i FilterMenuRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BasePrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageByKeyset = `-- name: PageByKeyset :many
SELECT id, name, base_price
FROM drinks
WHERE (base_price, id) < ($1, $2)
ORDER BY base_price DESC, id DESC
LIMIT $3
`

type PageByKeysetParams struct {
	AfterPrice int64 `json:"after_price"`
	AfterID    int64 `json:"after_id"`
	PageSize   int32 `json:"page_size"`
}

type PageByKeysetRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	BasePrice int64  `json:"base_price"`
}

// Keyset-пагинация: вместо «пропусти N» — «дай строки ПОСЛЕ вот этой». Курсор —
// значения сортировки последней строки прошлой страницы (after_price, after_id).
// Сравнение кортежей (base_price, id) < (after_price, after_id) ровно повторяет
// порядок ORDER BY base_price DESC, id DESC. Первую страницу берём с «сторожевым»
// курсором (заведомо больше любой строки). По индексу (base_price, id) это
// index range scan без отбрасывания — глубина страницы не дорожает.
func (q *Queries) PageByKeyset(ctx context.Context, arg PageByKeysetParams) ([]PageByKeysetRow, error) {
	rows, err := q.db.Query(ctx, pageByKeyset, arg.AfterPrice, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageByKeysetRow{}
	for rows.Next() {
		var i PageByKeysetRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BasePrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageByOffset = `-- name: PageByOffset :many
SELECT id, name, base_price
FROM drinks
ORDER BY base_price DESC, id DESC
LIMIT $2 OFFSET $1
`

type PageByOffsetParams struct {
	Skip     int32 `json:"skip"`
	PageSize int32 `json:"page_size"`
}

type PageByOffsetRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	BasePrice int64  `json:"base_price"`
}

// Пагинация через OFFSET: «пропусти offset строк, отдай следующие N». Просто, но
// сервер всё равно вычисляет и отбрасывает первые offset строк — на глубоких
// страницах это растёт линейно (см. README, «Заборчик»). ORDER BY обязан быть
// полным (цена + id как tie-break), иначе строки с равной ценой «плавают».
func (q *Queries) PageByOffset(ctx context.Context, arg PageByOffsetParams) ([]PageByOffsetRow, error) {
	rows, err := q.db.Query(ctx, pageByOffset, arg.Skip, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageByOffsetRow{}
	for rows.Next() {
		var i PageByOffsetRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BasePrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
