// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — как достать ровно нужные строки в нужном порядке и листать их
	// постранично. WHERE/ORDER/LIMIT — основа; затем два способа пагинации: OFFSET
	// (простой, но дорогой на глубоких страницах) и keyset (по «курсору» из
	// последней строки — летит по индексу).
	// WHERE/ORDER/LIMIT: отбираем категорию, сортируем по цене, берём не больше N.
	// Полный порядок здесь не критичен (одна категория, печатаем как есть).
	FilterMenu(ctx context.Context, arg FilterMenuParams) ([]FilterMenuRow, error)
	// Keyset-пагинация: вместо «пропусти N» — «дай строки ПОСЛЕ вот этой». Курсор —
	// значения сортировки последней строки прошлой страницы (after_price, after_id).
	// Сравнение кортежей (base_price, id) < (after_price, after_id) ровно повторяет
	// порядок ORDER BY base_price DESC, id DESC. Первую страницу берём с «сторожевым»
	// курсором (заведомо больше любой строки). По индексу (base_price, id) это
	// index range scan без отбрасывания — глубина страницы не дорожает.
	PageByKeyset(ctx context.Context, arg PageByKeysetParams) ([]PageByKeysetRow, error)
	// Пагинация через OFFSET: «пропусти offset строк, отдай следующие N». Просто, но
	// сервер всё равно вычисляет и отбрасывает первые offset строк — на глубоких
	// страницах это растёт линейно (см. README, «Заборчик»). ORDER BY обязан быть
	// полным (цена + id как tie-break), иначе строки с равной ценой «плавают».
	PageByOffset(ctx context.Context, arg PageByOffsetParams) ([]PageByOffsetRow, error)
}

var _ Querier = (*Queries)(nil)
