// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const customerSpend = `-- name: CustomerSpend :many

WITH order_totals AS (
    SELECT
        o.id                                  AS order_id,
        o.customer_id                         AS customer_id,
        sum(oi.quantity * oi.unit_price)::bigint AS cents
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.id
    GROUP BY o.id, o.customer_id
),
per_customer AS (
    SELECT
        t.customer_id        AS customer_id,
        count(*)             AS orders,
        sum(t.cents)::bigint AS spent
    FROM order_totals t
    GROUP BY t.customer_id
)
SELECT c.name AS customer, p.orders AS orders, p.spent AS spent
FROM per_customer p
JOIN customers c ON c.id::text = p.customer_id
ORDER BY p.spent DESC
`

type CustomerSpendRow struct {
	Customer string `json:"customer"`
	Orders   int64  `json:"orders"`
	Spent    int64  `json:"spent"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — CTE (Common Table Expression, секция WITH): именованный временный
// результат, на который ссылается основной запрос. CTE разбивает сложный запрос
// на читаемые шаги-«кирпичи» и позволяет переиспользовать промежуточный результат.
// Плюс — материализация: когда Postgres вычисляет CTE отдельно (фенс), а когда
// встраивает его в основной запрос.
// CTE-конвейер из двух шагов. order_totals: сумма каждого заказа из позиций
// (order_items). per_customer: сворачиваем заказы по клиенту. Основной запрос
// подставляет имя клиента. Без CTE это был бы вложенный подзапрос в подзапросе —
// здесь же читается сверху вниз, шаг за шагом.
func (q *Queries) CustomerSpend(ctx context.Context) ([]CustomerSpendRow, error) {
	rows, err := q.db.Query(ctx, customerSpend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerSpendRow{}
	for rows.Next() {
		var i CustomerSpendRow
		if err := rows.Scan(&i.Customer, &i.Orders, &i.Spent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderShareOfTotal = `-- name: OrderShareOfTotal :many
WITH order_totals AS MATERIALIZED (
    SELECT
        o.id                                  AS order_id,
        sum(oi.quantity * oi.unit_price)::bigint AS cents
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.id
    GROUP BY o.id
)
SELECT
    order_id,
    cents,
    round(100.0 * cents / (SELECT sum(cents) FROM order_totals), 1)::text AS pct
FROM order_totals
ORDER BY order_id
`

type OrderShareOfTotalRow struct {
	OrderID int64  `json:"order_id"`
	Cents   int64  `json:"cents"`
	Pct     string `json:"pct"`
}

// CTE, использованный ДВАЖДЫ: order_totals читается и в FROM, и в scalar-
// подзапросе (общий итог). Когда CTE ссылаются более одного раза, Postgres по
// умолчанию его МАТЕРИАЛИЗУЕТ — вычисляет один раз и переиспользует, а не считает
// заново на каждую ссылку. Здесь пишем AS MATERIALIZED явно (для одной ссылки
// умолчание иное — встраивание; противоположный рычаг — NOT MATERIALIZED).
func (q *Queries) OrderShareOfTotal(ctx context.Context) ([]OrderShareOfTotalRow, error) {
	rows, err := q.db.Query(ctx, orderShareOfTotal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderShareOfTotalRow{}
	for rows.Next() {
		var i OrderShareOfTotalRow
		if err := rows.Scan(&i.OrderID, &i.Cents, &i.Pct); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
