// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — CTE (Common Table Expression, секция WITH): именованный временный
	// результат, на который ссылается основной запрос. CTE разбивает сложный запрос
	// на читаемые шаги-«кирпичи» и позволяет переиспользовать промежуточный результат.
	// Плюс — материализация: когда Postgres вычисляет CTE отдельно (фенс), а когда
	// встраивает его в основной запрос.
	// CTE-конвейер из двух шагов. order_totals: сумма каждого заказа из позиций
	// (order_items). per_customer: сворачиваем заказы по клиенту. Основной запрос
	// подставляет имя клиента. Без CTE это был бы вложенный подзапрос в подзапросе —
	// здесь же читается сверху вниз, шаг за шагом.
	CustomerSpend(ctx context.Context) ([]CustomerSpendRow, error)
	// CTE, использованный ДВАЖДЫ: order_totals читается и в FROM, и в scalar-
	// подзапросе (общий итог). Когда CTE ссылаются более одного раза, Postgres по
	// умолчанию его МАТЕРИАЛИЗУЕТ — вычисляет один раз и переиспользует, а не считает
	// заново на каждую ссылку. Здесь пишем AS MATERIALIZED явно (для одной ссылки
	// умолчание иное — встраивание; противоположный рычаг — NOT MATERIALIZED).
	OrderShareOfTotal(ctx context.Context) ([]OrderShareOfTotalRow, error)
}

var _ Querier = (*Queries)(nil)
