// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const credit = `-- name: Credit :execrows
UPDATE ledger_accounts
SET balance = balance + $1
WHERE id = $2
`

type CreditParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

// Зачисление. :execrows == 0 значит «получателя не существует» — повод
// откатить весь перевод (см. сценарий 3 в main.go).
func (q *Queries) Credit(ctx context.Context, arg CreditParams) (int64, error) {
	result, err := q.db.Exec(ctx, credit, arg.Amount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const debit = `-- name: Debit :execrows
UPDATE ledger_accounts
SET balance = balance - $1
WHERE id = $2
`

type DebitParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

// Списание. CHECK (balance >= 0) в схеме отвергает уход в минус (SQLSTATE
// 23514) — это и роняет транзакцию при overdraft. :execrows отдаёт число
// затронутых строк: 0 значит «счёта с таким id нет».
func (q *Queries) Debit(ctx context.Context, arg DebitParams) (int64, error) {
	result, err := q.db.Exec(ctx, debit, arg.Amount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, owner, balance FROM ledger_accounts ORDER BY id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerAccount{}
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(&i.ID, &i.Owner, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedAccount = `-- name: SeedAccount :exec
INSERT INTO ledger_accounts (owner, balance) VALUES ($1, $2)
`

type SeedAccountParams struct {
	Owner   string `json:"owner"`
	Balance int64  `json:"balance"`
}

func (q *Queries) SeedAccount(ctx context.Context, arg SeedAccountParams) error {
	_, err := q.db.Exec(ctx, seedAccount, arg.Owner, arg.Balance)
	return err
}

const totalBalance = `-- name: TotalBalance :one
SELECT COALESCE(SUM(balance), 0)::bigint FROM ledger_accounts
`

// Сумма всех счетов — инвариант системы. Перевод денег НЕ должен её менять
// (C в ACID: консистентность). COALESCE на случай пустой таблицы.
func (q *Queries) TotalBalance(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalBalance)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const truncateAccounts = `-- name: TruncateAccounts :exec

TRUNCATE ledger_accounts RESTART IDENTITY
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — транзакции и ACID. Перевод денег между счетами — две команды
// (списать у одного, зачислить другому), которые обязаны примениться вместе
// или никак: это атомарность (A в ACID). Запросы тут — кирпичики; собирает их
// в одну транзакцию main.go (BEGIN → Debit → Credit → COMMIT, иначе ROLLBACK).
// Перед демо обнуляем таблицу и счётчик IDENTITY — id всегда 1..2, вывод
// воспроизводим независимо от числа прогонов.
func (q *Queries) TruncateAccounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAccounts)
	return err
}
