// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Зачисление. :execrows == 0 значит «получателя не существует» — повод
	// откатить весь перевод (см. сценарий 3 в main.go).
	Credit(ctx context.Context, arg CreditParams) (int64, error)
	// Списание. CHECK (balance >= 0) в схеме отвергает уход в минус (SQLSTATE
	// 23514) — это и роняет транзакцию при overdraft. :execrows отдаёт число
	// затронутых строк: 0 значит «счёта с таким id нет».
	Debit(ctx context.Context, arg DebitParams) (int64, error)
	ListAccounts(ctx context.Context) ([]LedgerAccount, error)
	SeedAccount(ctx context.Context, arg SeedAccountParams) error
	// Сумма всех счетов — инвариант системы. Перевод денег НЕ должен её менять
	// (C в ACID: консистентность). COALESCE на случай пустой таблицы.
	TotalBalance(ctx context.Context) (int64, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — транзакции и ACID. Перевод денег между счетами — две команды
	// (списать у одного, зачислить другому), которые обязаны примениться вместе
	// или никак: это атомарность (A в ACID). Запросы тут — кирпичики; собирает их
	// в одну транзакцию main.go (BEGIN → Debit → Credit → COMMIT, иначе ROLLBACK).
	// Перед демо обнуляем таблицу и счётчик IDENTITY — id всегда 1..2, вывод
	// воспроизводим независимо от числа прогонов.
	TruncateAccounts(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
