// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — DISTINCT ON: вернуть ровно ПО ОДНОЙ строке на группу, причём целую
	// строку (а не только агрегаты по ней). Классическая задача — «последний заказ
	// каждого клиента»: GROUP BY дал бы max(created_at), но не сам заказ; оконные
	// функции (08-02) умеют это через ROW_NUMBER()=1, а в Postgres есть короткий
	// путь — DISTINCT ON.
	// DISTINCT ON (o.customer_id) оставляет ПЕРВУЮ строку в каждой группе
	// customer_id — а какая «первая», решает ORDER BY. Ключевое правило: ORDER BY
	// обязан НАЧИНАТЬСЯ с выражения DISTINCT ON, а дальше идёт «по какому критерию
	// выбрать строку группы». Здесь дальше — created_at DESC (самый свежий) и id DESC
	// как tie-break. Итог: один, самый последний заказ на клиента.
	LatestOrderPerCustomer(ctx context.Context) ([]LatestOrderPerCustomerRow, error)
	// Тот же DISTINCT ON, но «победителя» группы выбираем по другому критерию —
	// меняем хвост ORDER BY на amount DESC. Получаем самый ДОРОГОЙ заказ на клиента.
	// Видно, что DISTINCT ON гибкий: что стоит после выражения группировки в
	// ORDER BY, то и определяет, какая строка останется.
	PriciestOrderPerCustomer(ctx context.Context) ([]PriciestOrderPerCustomerRow, error)
}

var _ Querier = (*Queries)(nil)
