// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const latestOrderPerCustomer = `-- name: LatestOrderPerCustomer :many

SELECT DISTINCT ON (o.customer_id)
    c.name                  AS customer,
    o.id                    AS order_id,
    o.amount::numeric(10, 2)::text AS amount,
    o.status                AS status,
    o.created_at::date::text AS day
FROM orders o
JOIN customers c ON c.id::text = o.customer_id
ORDER BY o.customer_id, o.created_at DESC, o.id DESC
`

type LatestOrderPerCustomerRow struct {
	Customer string `json:"customer"`
	OrderID  int64  `json:"order_id"`
	Amount   string `json:"amount"`
	Status   string `json:"status"`
	Day      string `json:"day"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — DISTINCT ON: вернуть ровно ПО ОДНОЙ строке на группу, причём целую
// строку (а не только агрегаты по ней). Классическая задача — «последний заказ
// каждого клиента»: GROUP BY дал бы max(created_at), но не сам заказ; оконные
// функции (08-02) умеют это через ROW_NUMBER()=1, а в Postgres есть короткий
// путь — DISTINCT ON.
// DISTINCT ON (o.customer_id) оставляет ПЕРВУЮ строку в каждой группе
// customer_id — а какая «первая», решает ORDER BY. Ключевое правило: ORDER BY
// обязан НАЧИНАТЬСЯ с выражения DISTINCT ON, а дальше идёт «по какому критерию
// выбрать строку группы». Здесь дальше — created_at DESC (самый свежий) и id DESC
// как tie-break. Итог: один, самый последний заказ на клиента.
func (q *Queries) LatestOrderPerCustomer(ctx context.Context) ([]LatestOrderPerCustomerRow, error) {
	rows, err := q.db.Query(ctx, latestOrderPerCustomer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestOrderPerCustomerRow{}
	for rows.Next() {
		var i LatestOrderPerCustomerRow
		if err := rows.Scan(
			&i.Customer,
			&i.OrderID,
			&i.Amount,
			&i.Status,
			&i.Day,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priciestOrderPerCustomer = `-- name: PriciestOrderPerCustomer :many
SELECT DISTINCT ON (o.customer_id)
    c.name                  AS customer,
    o.id                    AS order_id,
    o.amount::numeric(10, 2)::text AS amount
FROM orders o
JOIN customers c ON c.id::text = o.customer_id
ORDER BY o.customer_id, o.amount DESC, o.id DESC
`

type PriciestOrderPerCustomerRow struct {
	Customer string `json:"customer"`
	OrderID  int64  `json:"order_id"`
	Amount   string `json:"amount"`
}

// Тот же DISTINCT ON, но «победителя» группы выбираем по другому критерию —
// меняем хвост ORDER BY на amount DESC. Получаем самый ДОРОГОЙ заказ на клиента.
// Видно, что DISTINCT ON гибкий: что стоит после выражения группировки в
// ORDER BY, то и определяет, какая строка останется.
func (q *Queries) PriciestOrderPerCustomer(ctx context.Context) ([]PriciestOrderPerCustomerRow, error) {
	rows, err := q.db.Query(ctx, priciestOrderPerCustomer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriciestOrderPerCustomerRow{}
	for rows.Next() {
		var i PriciestOrderPerCustomerRow
		if err := rows.Scan(&i.Customer, &i.OrderID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
