// Команда demo юнита 02-01: кто владеет первичным ключом — БД или приложение.
//
// Два режима:
//
//	demo          — GENERATED ALWAYS vs BY DEFAULT vs обычный DEFAULT;
//	demo -reset   — накатить канон Brew + таблицы юнита и выйти (db-reset).
//
// Логи — в stderr, stdout — только результат (для вставки в README дословно).
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/jackc/pgx/v5/pgconn"

	"github.com/dsbasko/postgres-cookbook/lectures/02-schema-and-constraints/02-01-identity-and-defaults/internal/db"
	"github.com/dsbasko/postgres-cookbook/lectures/internal/brew"
	"github.com/dsbasko/postgres-cookbook/lectures/internal/log"
	"github.com/dsbasko/postgres-cookbook/lectures/internal/pg"
	"github.com/dsbasko/postgres-cookbook/lectures/internal/runctx"
)

func main() {
	logger := log.New()

	reset := flag.Bool("reset", false, "накатить канон Brew + таблицы юнита и выйти")
	flag.Parse()

	ctx, cancel := runctx.New()
	defer cancel()

	if err := run(ctx, *reset); err != nil && !errors.Is(err, context.Canceled) {
		logger.Error("demo failed", "err", err)
		os.Exit(1)
	}
}

func run(ctx context.Context, reset bool) error {
	pool, err := pg.NewPool(ctx)
	if err != nil {
		return fmt.Errorf("pg.NewPool: %w", err)
	}
	defer pool.Close()

	if err := pool.Ping(ctx); err != nil {
		return fmt.Errorf("ping (песочница поднята? `docker compose up -d`): %w", err)
	}

	if reset {
		ddl, err := schemaDDL()
		if err != nil {
			return err
		}
		if err := brew.Apply(ctx, pool, ddl); err != nil {
			return fmt.Errorf("brew.Apply: %w", err)
		}
		fmt.Println("Канон Brew + таблицы id_always/id_by_default накатаны.")
		return nil
	}

	queries := db.New(pool)

	// Чистим обе таблицы — id всегда стартуют с 1, вывод воспроизводим.
	if err := queries.ResetIdAlways(ctx); err != nil {
		return fmt.Errorf("ResetIdAlways: %w", err)
	}
	if err := queries.ResetIdByDefault(ctx); err != nil {
		return fmt.Errorf("ResetIdByDefault: %w", err)
	}

	// 1) GENERATED ALWAYS: три INSERT без id → база раздаёт 1,2,3; DEFAULT now()
	// заполняет created_at.
	var ids []int64
	var createdFilled bool
	for _, label := range []string{"espresso", "cappuccino", "latte"} {
		row, err := queries.InsertAlways(ctx, label)
		if err != nil {
			return fmt.Errorf("InsertAlways: %w", err)
		}
		ids = append(ids, row.ID)
		createdFilled = row.CreatedAtFilled
	}
	fmt.Println("1) GENERATED ALWAYS AS IDENTITY — id присваивает БД:")
	fmt.Printf("   три INSERT без id → id = %v; created_at заполнен по DEFAULT now(): %v\n", ids, createdFilled)

	// 2) Явный id в GENERATED ALWAYS — отклонён базой (приложение не владелец).
	err = queries.InsertAlwaysExplicitID(ctx, db.InsertAlwaysExplicitIDParams{ID: 999, Label: "smuggled"})
	fmt.Printf("2) Явный id=999 в GENERATED ALWAYS → отклонён: SQLSTATE %s (нельзя писать в GENERATED ALWAYS)\n", sqlState(err))

	// 3) Явный id в GENERATED BY DEFAULT — принят (поведение serial).
	byDefID, err := queries.InsertByDefaultExplicitID(ctx, db.InsertByDefaultExplicitIDParams{ID: 999, Label: "ok"})
	if err != nil {
		return fmt.Errorf("InsertByDefaultExplicitID: %w", err)
	}
	fmt.Printf("3) Явный id=999 в GENERATED BY DEFAULT → принят: id = %d\n", byDefID)
	fmt.Println("   (счётчик IDENTITY при этом не сдвинулся — отсюда классический рассинхрон serial; см. заборчик)")

	return nil
}

// sqlState достаёт SQLSTATE-код из ошибки Postgres. Код детерминирован (в отличие
// от текста сообщения), поэтому его и печатаем — вывод воспроизводится дословно.
func sqlState(err error) string {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return pgErr.Code
	}
	return "<нет ошибки>"
}

// schemaDDL читает schema.sql юнита (DDL поверх канона). Путь резолвится через
// runtime.Caller относительно этого исходника (go:embed не дотянется: файл лежит
// на два уровня выше cmd/demo/).
func schemaDDL() (string, error) {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("runtime.Caller: не удалось определить путь к исходнику")
	}
	path := filepath.Join(filepath.Dir(thisFile), "..", "..", "schema.sql")
	b, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read schema.sql: %w", err)
	}
	return string(b), nil
}
