// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const customerOrderStats = `-- name: CustomerOrderStats :many
SELECT
    c.name                                          AS customer,
    count(*)                                        AS rows_in_group,
    count(o.id)                                     AS orders,
    (COALESCE(sum(o.amount), 0))::numeric(10, 2)::text AS revenue
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id::text
GROUP BY c.id, c.name
ORDER BY c.id
`

type CustomerOrderStatsRow struct {
	Customer    string `json:"customer"`
	RowsInGroup int64  `json:"rows_in_group"`
	Orders      int64  `json:"orders"`
	Revenue     string `json:"revenue"`
}

// GROUP BY по клиенту на customers LEFT JOIN orders. Ключевой момент урока:
//
//	count(*)     — считает СТРОКИ группы (у Карины строка одна, даже без заказа);
//	count(o.id)  — считает строки, где o.id НЕ NULL (у Карины таких нет → 0).
//
// Поэтому для клиента без заказов count(*)=1, а count(o.id)=0. sum по amount
// может быть NULL (нет заказов) → COALESCE к 0; приводим к numeric(10,2)::text
// для стабильного «Ц.КК» в выводе.
func (q *Queries) CustomerOrderStats(ctx context.Context) ([]CustomerOrderStatsRow, error) {
	rows, err := q.db.Query(ctx, customerOrderStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerOrderStatsRow{}
	for rows.Next() {
		var i CustomerOrderStatsRow
		if err := rows.Scan(
			&i.Customer,
			&i.RowsInGroup,
			&i.Orders,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuStatsByCategory = `-- name: MenuStatsByCategory :many

SELECT
    category                       AS category,
    count(*)                       AS drinks,
    min(base_price)::bigint        AS price_min,
    max(base_price)::bigint        AS price_max,
    round(avg(base_price))::bigint AS price_avg
FROM drinks
GROUP BY category
ORDER BY category
`

type MenuStatsByCategoryRow struct {
	Category string `json:"category"`
	Drinks   int64  `json:"drinks"`
	PriceMin int64  `json:"price_min"`
	PriceMax int64  `json:"price_max"`
	PriceAvg int64  `json:"price_avg"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — агрегация: схлопнуть много строк в сводку. GROUP BY режет таблицу на
// группы, агрегатные функции (count/sum/min/max/avg) считают по каждой, HAVING
// фильтрует уже ГОТОВЫЕ группы. И коварная пара: count(*) vs count(колонка) —
// они считают разное, и на LEFT JOIN это видно невооружённым глазом.
// GROUP BY category: одна строка-сводка на категорию. count(*) — сколько
// напитков, min/max — границы цены, avg — средняя (округляем до целых центов и
// приводим к bigint, чтобы в Go это был int64, а не numeric).
func (q *Queries) MenuStatsByCategory(ctx context.Context) ([]MenuStatsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, menuStatsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuStatsByCategoryRow{}
	for rows.Next() {
		var i MenuStatsByCategoryRow
		if err := rows.Scan(
			&i.Category,
			&i.Drinks,
			&i.PriceMin,
			&i.PriceMax,
			&i.PriceAvg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regularCustomers = `-- name: RegularCustomers :many
SELECT
    c.name                                          AS customer,
    count(o.id)                                     AS orders,
    (COALESCE(sum(o.amount), 0))::numeric(10, 2)::text AS revenue
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id::text
GROUP BY c.id, c.name
HAVING count(o.id) >= 2
ORDER BY c.id
`

type RegularCustomersRow struct {
	Customer string `json:"customer"`
	Orders   int64  `json:"orders"`
	Revenue  string `json:"revenue"`
}

// HAVING фильтрует ГРУППЫ (не строки — для строк есть WHERE). Оставляем только
// клиентов с двумя и более заказами. WHERE так нельзя: count(o.id) ещё не
// посчитан на этапе WHERE, он появляется только после группировки.
func (q *Queries) RegularCustomers(ctx context.Context) ([]RegularCustomersRow, error) {
	rows, err := q.db.Query(ctx, regularCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegularCustomersRow{}
	for rows.Next() {
		var i RegularCustomersRow
		if err := rows.Scan(&i.Customer, &i.Orders, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
