// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const abovePriceAvg = `-- name: AbovePriceAvg :many

SELECT id, name, base_price
FROM drinks
WHERE base_price > (SELECT avg(base_price) FROM drinks)
ORDER BY base_price
`

type AbovePriceAvgRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	BasePrice int64  `json:"base_price"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — подзапросы и выбор между IN и EXISTS. Три формы: scalar (подзапрос как
// одно значение), IN (значение в наборе), EXISTS (есть ли совпадающая строка). И
// кульминация — почему «нет среди» пишут через NOT EXISTS, а не NOT IN: ловушка
// NULL в списке (мы встречали её в 03-06 как урок о NULL; здесь это довод за
// EXISTS).
// Scalar-подзапрос: (SELECT avg(base_price) FROM drinks) возвращает ОДНО число
// (среднюю цену = 400), и оно подставляется в WHERE как обычное значение.
// Получаем напитки дороже среднего.
func (q *Queries) AbovePriceAvg(ctx context.Context) ([]AbovePriceAvgRow, error) {
	rows, err := q.db.Query(ctx, abovePriceAvg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AbovePriceAvgRow{}
	for rows.Next() {
		var i AbovePriceAvgRow
		if err := rows.Scan(&i.ID, &i.Name, &i.BasePrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCustomersWithOrders = `-- name: CountCustomersWithOrders :one
SELECT count(*)
FROM customers c
WHERE EXISTS (
    SELECT 1 FROM orders o WHERE o.customer_id = c.id::text
)
`

// EXISTS — коррелированный подзапрос: для каждого клиента спрашиваем «есть ли
// ХОТЯ БЫ ОДИН его заказ». EXISTS останавливается на первой найденной строке и
// не тащит данные наружу — ему важен факт наличия, а не значения. Карина без
// заказов не пройдёт.
func (q *Queries) CountCustomersWithOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersWithOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotFeaturedNotExists = `-- name: CountNotFeaturedNotExists :one
SELECT count(*)
FROM drinks d
WHERE NOT EXISTS (
    SELECT 1 FROM promo p WHERE p.featured_drink_id = d.id
)
`

// Правильно: NOT EXISTS. Спрашиваем «нет ли акции на ЭТОТ напиток». Строка promo
// с featured_drink_id = NULL ни с каким d.id не совпадёт (NULL ни с чем не
// равен), поэтому никого лишнего не исключает. Итог 4 (пять напитков минус
// эспрессо #1, который на акции).
func (q *Queries) CountNotFeaturedNotExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNotFeaturedNotExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotFeaturedNotIn = `-- name: CountNotFeaturedNotIn :one
SELECT count(*)
FROM drinks
WHERE id NOT IN (SELECT featured_drink_id FROM promo)
`

// Ловушка: id NOT IN (1, NULL). Для напитка с id<>1 это NOT (id=1 OR id=NULL) =
// NOT (false OR NULL) = NOT (NULL) = NULL → строка НЕ проходит фильтр. Итог 0,
// хотя «не на акции» напитков явно больше. NULL в списке обнуляет весь NOT IN.
func (q *Queries) CountNotFeaturedNotIn(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNotFeaturedNotIn)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const drinksOrdered = `-- name: DrinksOrdered :many
SELECT id, name
FROM drinks
WHERE id IN (SELECT drink_id FROM order_items)
ORDER BY id
`

type DrinksOrderedRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// IN-подзапрос: id IN (набор из подзапроса). «Напитки, которые хоть раз
// заказывали» — те, чей id есть среди order_items.drink_id. Зелёный чай (#5) не
// заказывали ни разу → его тут не будет.
func (q *Queries) DrinksOrdered(ctx context.Context) ([]DrinksOrderedRow, error) {
	rows, err := q.db.Query(ctx, drinksOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DrinksOrderedRow{}
	for rows.Next() {
		var i DrinksOrderedRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedPromo = `-- name: SeedPromo :exec
INSERT INTO promo (title, featured_drink_id) VALUES
    ('Эспрессо дня', 1),
    ('Скидка на всё', NULL)
`

// Две акции: на эспрессо (#1) и на всё меню (featured_drink_id = NULL). Этого
// одного NULL достаточно, чтобы сломать NOT IN ниже.
func (q *Queries) SeedPromo(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedPromo)
	return err
}

const truncatePromo = `-- name: TruncatePromo :exec
TRUNCATE promo
`

func (q *Queries) TruncatePromo(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncatePromo)
	return err
}
