// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — две вещи: (1) JOIN тянется через сколько угодно таблиц, и (2) таблицу
	// можно соединить саму с собой (self-join). Чек заказа собираем из четырёх
	// таблиц канона; иерархию персонала — self-join'ом лабораторной staff.
	// Многотабличный JOIN: orders → customers → order_items → drinks. Каждый JOIN
	// добавляет по таблице через свой ключ. Получаем «чек»: по строке на позицию
	// заказа с именем клиента, названием напитка, количеством и суммой строки.
	OrderReceipt(ctx context.Context) ([]OrderReceiptRow, error)
	// Анна — старший менеджер (manager_id NULL); остальные подчинены ей. Анна стоит
	// первой строкой: FK manager_id ссылается на уже вставленную строку этой же
	// таблицы.
	SeedStaff(ctx context.Context) error
	// Self-join: одна и та же таблица staff участвует дважды под разными псевдонимами
	// — e (employee) и m (manager). Связь e.manager_id = m.id «разворачивает» ссылку
	// в имя руководителя. LEFT JOIN, потому что у Анны руководителя нет → manager
	// придёт NULL (а не выкинет её из списка).
	StaffWithManager(ctx context.Context) ([]StaffWithManagerRow, error)
	TruncateStaff(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
