// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const orderReceipt = `-- name: OrderReceipt :many

SELECT
    o.id                          AS order_id,
    c.name                        AS customer,
    d.name                        AS drink,
    oi.quantity                            AS quantity,
    oi.unit_price                          AS unit_price,
    (oi.quantity * oi.unit_price)::bigint  AS line_total
FROM orders o
JOIN customers c   ON c.id::text = o.customer_id
JOIN order_items oi ON oi.order_id = o.id
JOIN drinks d      ON d.id = oi.drink_id
ORDER BY o.id, oi.id
`

type OrderReceiptRow struct {
	OrderID   int64  `json:"order_id"`
	Customer  string `json:"customer"`
	Drink     string `json:"drink"`
	Quantity  int32  `json:"quantity"`
	UnitPrice int64  `json:"unit_price"`
	LineTotal int64  `json:"line_total"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — две вещи: (1) JOIN тянется через сколько угодно таблиц, и (2) таблицу
// можно соединить саму с собой (self-join). Чек заказа собираем из четырёх
// таблиц канона; иерархию персонала — self-join'ом лабораторной staff.
// Многотабличный JOIN: orders → customers → order_items → drinks. Каждый JOIN
// добавляет по таблице через свой ключ. Получаем «чек»: по строке на позицию
// заказа с именем клиента, названием напитка, количеством и суммой строки.
func (q *Queries) OrderReceipt(ctx context.Context) ([]OrderReceiptRow, error) {
	rows, err := q.db.Query(ctx, orderReceipt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderReceiptRow{}
	for rows.Next() {
		var i OrderReceiptRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Customer,
			&i.Drink,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedStaff = `-- name: SeedStaff :exec
INSERT INTO staff (id, name, role, manager_id) VALUES
    (1, 'Анна', 'manager',    NULL),
    (2, 'Борис', 'barista',   1),
    (3, 'Вера', 'barista',    1),
    (4, 'Глеб', 'shift-lead', 1)
`

// Анна — старший менеджер (manager_id NULL); остальные подчинены ей. Анна стоит
// первой строкой: FK manager_id ссылается на уже вставленную строку этой же
// таблицы.
func (q *Queries) SeedStaff(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedStaff)
	return err
}

const staffWithManager = `-- name: StaffWithManager :many
SELECT e.name AS employee, e.role, m.name AS manager
FROM staff e
LEFT JOIN staff m ON m.id = e.manager_id
ORDER BY e.id
`

type StaffWithManagerRow struct {
	Employee string      `json:"employee"`
	Role     string      `json:"role"`
	Manager  pgtype.Text `json:"manager"`
}

// Self-join: одна и та же таблица staff участвует дважды под разными псевдонимами
// — e (employee) и m (manager). Связь e.manager_id = m.id «разворачивает» ссылку
// в имя руководителя. LEFT JOIN, потому что у Анны руководителя нет → manager
// придёт NULL (а не выкинет её из списка).
func (q *Queries) StaffWithManager(ctx context.Context) ([]StaffWithManagerRow, error) {
	rows, err := q.db.Query(ctx, staffWithManager)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffWithManagerRow{}
	for rows.Next() {
		var i StaffWithManagerRow
		if err := rows.Scan(&i.Employee, &i.Role, &i.Manager); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateStaff = `-- name: TruncateStaff :exec
TRUNCATE staff
`

func (q *Queries) TruncateStaff(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateStaff)
	return err
}
