-- query.sql — протагонист урока. `make gen` → типизированный pgx-код в
-- internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
--
-- Тема — два режима IDENTITY и обычный DEFAULT. GENERATED ALWAYS отдаёт
-- владение ключом базе (приложение не может вписать свой id); GENERATED BY
-- DEFAULT ведёт себя как serial — примет и явный id. Демонстрируем оба и
-- обычный DEFAULT (now()), значение которого подставляется при пропуске.

-- name: ResetIdAlways :exec
-- Перед демо обнуляем таблицу и счётчик IDENTITY — вывод воспроизводим
-- (id всегда стартуют с 1) независимо от числа прогонов.
TRUNCATE id_always RESTART IDENTITY;

-- name: ResetIdByDefault :exec
TRUNCATE id_by_default RESTART IDENTITY;

-- name: InsertAlways :one
-- id не передаём — его присваивает БД из IDENTITY; created_at не передаём — его
-- подставляет DEFAULT now(). Возвращаем id и факт, что DEFAULT сработал.
INSERT INTO id_always (label) VALUES ($1)
RETURNING id, (created_at IS NOT NULL)::boolean AS created_at_filled;

-- name: InsertAlwaysExplicitID :exec
-- Попытка задать id вручную в GENERATED ALWAYS — БД отклонит (SQLSTATE 428C9):
-- владелец колонки — база, а не приложение.
INSERT INTO id_always (id, label) VALUES ($1, $2);

-- name: InsertByDefaultExplicitID :one
-- В GENERATED BY DEFAULT (как serial) явный id принимается. Счётчик IDENTITY при
-- этом НЕ двигается — отсюда классический рассинхрон serial (см. README).
INSERT INTO id_by_default (id, label) VALUES ($1, $2)
RETURNING id;
