-- schema.sql — DDL-добавки ЭТОГО юнита поверх канона Brew (schema/brew.sql).
--
-- Тема — кто владеет первичным ключом: БД или приложение. Канон Brew байт-
-- совместим с kafka-cookbook (его id-колонки трогать нельзя), поэтому контраст
-- IDENTITY-режимов показываем на двух СВОИХ таблицах.
--
-- DDL применяется двумя путями: sqlc читает его на `make gen`, а демо встраивает
-- через runtime.Caller и накатывает brew.Apply при db-reset. Поэтому он
-- идемпотентен (CREATE TABLE IF NOT EXISTS).

-- id_always — современный дефолт PG18: GENERATED ALWAYS AS IDENTITY. Колонкой
-- владеет БД: своё значение в неё не вписать (нужен OVERRIDING SYSTEM VALUE).
-- created_at — обычный DEFAULT: значение подставляется, если его не передали.
CREATE TABLE IF NOT EXISTS id_always (
    id          BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    label       TEXT         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- id_by_default — GENERATED BY DEFAULT AS IDENTITY (поведение старого serial):
-- БД подставит id, если его не дали, но и явный id примет — а это и есть тропинка
-- к рассинхрону последовательности (см. README, «Заборчик»).
CREATE TABLE IF NOT EXISTS id_by_default (
    id     BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label  TEXT    NOT NULL
);
