-- schema.sql — DDL-добавки ЭТОГО юнита поверх канона Brew (schema/brew.sql).
--
-- Юниту 03-02 своих таблиц не нужно: и фильтрацию (WHERE/ORDER/LIMIT), и
-- keyset-пагинацию мы показываем на каноне Brew (drinks, read-only). Файл
-- оставлен намеренно: он часть канонической анатомии юнита, и sqlc.yaml всегда
-- перечисляет [../../../schema/brew.sql, schema.sql].
