// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// id присваивает БД из DEFAULT uuidv7(); seq — из IDENTITY. Возвращаем оба, но
	// демо их не печатает (id случаен) — нужны только для проверки порядка.
	InsertSignup(ctx context.Context, email string) (InsertSignupRow, error)
	// Совпадает ли порядок по uuidv7-ключу (id) с порядком вставки (seq)? Для v7,
	// сгенерированного по возрастанию времени, — да: монотонный, сортируемый ключ.
	SignupsTimeOrdered(ctx context.Context) (SignupsTimeOrderedRow, error)
	// Перед демо чистим таблицу, чтобы вставка трёх строк давала ровно три (вывод
	// воспроизводим независимо от числа прогонов).
	TruncateSignups(ctx context.Context) error
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — uuid как ключ: случайный gen_random_uuid() (версия 4) против PG18
	// uuidv7() (версия 7, со встроенным временем). Значения uuid случайны, поэтому
	// печатать их нельзя (вывод не воспроизведётся) — вместо этого показываем
	// ПРОВЕРЯЕМЫЕ свойства: номер версии, наличие встроенного времени и монотонность
	// v7 как сортируемого ключа.
	// Детерминированные факты о версиях. v4 — случайный, версия 4, без встроенного
	// времени (uuid_extract_timestamp → NULL). v7 — версия 7, со встроенным
	// временем (uuid_extract_timestamp → не NULL).
	UUIDFacts(ctx context.Context) (UUIDFactsRow, error)
}

var _ Querier = (*Queries)(nil)
