// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSignup = `-- name: InsertSignup :one
INSERT INTO loyalty_signups (email) VALUES ($1)
RETURNING id, seq
`

type InsertSignupRow struct {
	ID  pgtype.UUID `json:"id"`
	Seq pgtype.Int8 `json:"seq"`
}

// id присваивает БД из DEFAULT uuidv7(); seq — из IDENTITY. Возвращаем оба, но
// демо их не печатает (id случаен) — нужны только для проверки порядка.
func (q *Queries) InsertSignup(ctx context.Context, email string) (InsertSignupRow, error) {
	row := q.db.QueryRow(ctx, insertSignup, email)
	var i InsertSignupRow
	err := row.Scan(&i.ID, &i.Seq)
	return i, err
}

const signupsTimeOrdered = `-- name: SignupsTimeOrdered :one
SELECT
    bool_and(id_rank = seq_rank)::boolean AS ids_match_insertion_order,
    count(*)::bigint                      AS n
FROM (
    SELECT row_number() OVER (ORDER BY id)  AS id_rank,
           row_number() OVER (ORDER BY seq) AS seq_rank
    FROM loyalty_signups
) t
`

type SignupsTimeOrderedRow struct {
	IdsMatchInsertionOrder bool  `json:"ids_match_insertion_order"`
	N                      int64 `json:"n"`
}

// Совпадает ли порядок по uuidv7-ключу (id) с порядком вставки (seq)? Для v7,
// сгенерированного по возрастанию времени, — да: монотонный, сортируемый ключ.
func (q *Queries) SignupsTimeOrdered(ctx context.Context) (SignupsTimeOrderedRow, error) {
	row := q.db.QueryRow(ctx, signupsTimeOrdered)
	var i SignupsTimeOrderedRow
	err := row.Scan(&i.IdsMatchInsertionOrder, &i.N)
	return i, err
}

const truncateSignups = `-- name: TruncateSignups :exec
TRUNCATE loyalty_signups RESTART IDENTITY
`

// Перед демо чистим таблицу, чтобы вставка трёх строк давала ровно три (вывод
// воспроизводим независимо от числа прогонов).
func (q *Queries) TruncateSignups(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateSignups)
	return err
}

const uUIDFacts = `-- name: UUIDFacts :one

SELECT
    uuid_extract_version(gen_random_uuid())::int         AS v4_version,
    uuid_extract_version(uuidv7())::int                  AS v7_version,
    (uuid_extract_timestamp(gen_random_uuid()) IS NULL)::boolean     AS v4_has_no_timestamp,
    (uuid_extract_timestamp(uuidv7()) IS NOT NULL)::boolean          AS v7_has_timestamp
`

type UUIDFactsRow struct {
	V4Version        int32 `json:"v4_version"`
	V7Version        int32 `json:"v7_version"`
	V4HasNoTimestamp bool  `json:"v4_has_no_timestamp"`
	V7HasTimestamp   bool  `json:"v7_has_timestamp"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — uuid как ключ: случайный gen_random_uuid() (версия 4) против PG18
// uuidv7() (версия 7, со встроенным временем). Значения uuid случайны, поэтому
// печатать их нельзя (вывод не воспроизведётся) — вместо этого показываем
// ПРОВЕРЯЕМЫЕ свойства: номер версии, наличие встроенного времени и монотонность
// v7 как сортируемого ключа.
// Детерминированные факты о версиях. v4 — случайный, версия 4, без встроенного
// времени (uuid_extract_timestamp → NULL). v7 — версия 7, со встроенным
// временем (uuid_extract_timestamp → не NULL).
func (q *Queries) UUIDFacts(ctx context.Context) (UUIDFactsRow, error) {
	row := q.db.QueryRow(ctx, uUIDFacts)
	var i UUIDFactsRow
	err := row.Scan(
		&i.V4Version,
		&i.V7Version,
		&i.V4HasNoTimestamp,
		&i.V7HasTimestamp,
	)
	return i, err
}
