// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const searchAnd = `-- name: SearchAnd :many
SELECT id, title
FROM kb_articles
WHERE tsv @@ to_tsquery('english', 'milk & cappuccino')
ORDER BY id
`

type SearchAndRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

// to_tsquery с оператором & — обе лексемы должны присутствовать. Находим статьи,
// где есть И milk, И cappuccino (plainto_tsquery соединил бы их тоже через &, но
// to_tsquery даёт явный контроль: |, &, !, <-> для фразового поиска).
func (q *Queries) SearchAnd(ctx context.Context) ([]SearchAndRow, error) {
	rows, err := q.db.Query(ctx, searchAnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAndRow{}
	for rows.Next() {
		var i SearchAndRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRanked = `-- name: SearchRanked :many
SELECT id, title,
       round(ts_rank(tsv, plainto_tsquery('english', 'brew'))::numeric, 4)::text AS rank
FROM kb_articles
WHERE tsv @@ plainto_tsquery('english', 'brew')
ORDER BY rank DESC, id
`

type SearchRankedRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Rank  string `json:"rank"`
}

// Поиск 'brew' с ранжированием. @@ — оператор совпадения tsvector ↔ tsquery.
// ts_rank учитывает веса: у статьи 2 'brew' есть и в заголовке (вес A), и в теле
// (B), поэтому её ранг выше, чем у статьи 1 (только тело). round(...)::text —
// стабильное печатаемое число (float ранга округляем до 4 знаков).
func (q *Queries) SearchRanked(ctx context.Context) ([]SearchRankedRow, error) {
	rows, err := q.db.Query(ctx, searchRanked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRankedRow{}
	for rows.Next() {
		var i SearchRankedRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showTsvector = `-- name: ShowTsvector :one

SELECT to_tsvector('english', body)::text AS tsv
FROM kb_articles
WHERE id = 2
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — полнотекстовый поиск: текст превращается в tsvector (нормализованные
// лексемы с позициями), запрос — в tsquery, оператор @@ проверяет совпадение, а
// ts_rank ранжирует. В отличие от LIKE '%brew%', FTS понимает морфологию (brewing
// → brew) и игнорирует стоп-слова, а с GIN по tsv летит индексом (06-05).
// Что видит поиск: тело статьи 2, разобранное в tsvector. Заметь стемминг
// (brewing/brew → 'brew', temperature → 'temperatur', hours → 'hour') и
// выброшенные стоп-слова (is, about, not, for). Числа — позиции лексем в тексте.
func (q *Queries) ShowTsvector(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, showTsvector)
	var tsv string
	err := row.Scan(&tsv)
	return tsv, err
}

const stemmingMatch = `-- name: StemmingMatch :many
SELECT id, title
FROM kb_articles
WHERE tsv @@ plainto_tsquery('english', 'brewing')
ORDER BY id
`

type StemmingMatchRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

// Морфология бесплатно: запрос 'brewing' стеммится в 'brew' и находит статьи,
// где встречается 'brew'/'brewing' — то, чего LIKE '%brewing%' не дал бы.
func (q *Queries) StemmingMatch(ctx context.Context) ([]StemmingMatchRow, error) {
	rows, err := q.db.Query(ctx, stemmingMatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StemmingMatchRow{}
	for rows.Next() {
		var i StemmingMatchRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
