// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT count(*)::bigint AS n FROM fk_order
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countReviews = `-- name: CountReviews :one
SELECT
    count(*)::bigint                                   AS total,
    count(*) FILTER (WHERE customer_id IS NULL)::bigint AS null_customer
FROM fk_review
`

type CountReviewsRow struct {
	Total        int64 `json:"total"`
	NullCustomer int64 `json:"null_customer"`
}

func (q *Queries) CountReviews(ctx context.Context) (CountReviewsRow, error) {
	row := q.db.QueryRow(ctx, countReviews)
	var i CountReviewsRow
	err := row.Scan(&i.Total, &i.NullCustomer)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM fk_customer WHERE id = $1
`

// Запускает ON DELETE-политики детей: CASCADE удалит заказы, SET NULL обнулит
// ссылку в отзывах.
func (q *Queries) DeleteCustomer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const deleteDrink = `-- name: DeleteDrink :exec
DELETE FROM fk_drink WHERE id = $1
`

// Дефолтный FK fk_orderitem → fk_drink (NO ACTION): пока есть ссылка → 23503.
func (q *Queries) DeleteDrink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDrink, id)
	return err
}

const insertCustomer = `-- name: InsertCustomer :one
INSERT INTO fk_customer (name) VALUES ($1) RETURNING id
`

func (q *Queries) InsertCustomer(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, insertCustomer, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDrink = `-- name: InsertDrink :one
INSERT INTO fk_drink (name) VALUES ($1) RETURNING id
`

func (q *Queries) InsertDrink(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, insertDrink, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO fk_order (customer_id, note) VALUES ($1, $2)
`

type InsertOrderParams struct {
	CustomerID int64  `json:"customer_id"`
	Note       string `json:"note"`
}

// customer_id с несуществующим значением → SQLSTATE 23503 (FK не даёт повиснуть).
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder, arg.CustomerID, arg.Note)
	return err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO fk_orderitem (drink_id, qty) VALUES ($1, $2)
`

type InsertOrderItemParams struct {
	DrinkID int64 `json:"drink_id"`
	Qty     int32 `json:"qty"`
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem, arg.DrinkID, arg.Qty)
	return err
}

const insertReview = `-- name: InsertReview :exec
INSERT INTO fk_review (customer_id, stars) VALUES ($1, $2)
`

type InsertReviewParams struct {
	CustomerID pgtype.Int8 `json:"customer_id"`
	Stars      int32       `json:"stars"`
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) error {
	_, err := q.db.Exec(ctx, insertReview, arg.CustomerID, arg.Stars)
	return err
}

const resetFK = `-- name: ResetFK :exec

TRUNCATE fk_orderitem, fk_review, fk_order, fk_drink, fk_customer RESTART IDENTITY CASCADE
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — ссылочная целостность: FK не даёт сослаться на несуществующего
// родителя (23503), а ON DELETE решает судьбу детей при удалении родителя:
// CASCADE — удалить, SET NULL — обнулить ссылку, дефолт NO ACTION — запретить.
// CASCADE в TRUNCATE — это про сами таблицы (очистить и связанные), не путать с
// ON DELETE CASCADE внешнего ключа.
func (q *Queries) ResetFK(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetFK)
	return err
}
