// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountOrders(ctx context.Context) (int64, error)
	CountReviews(ctx context.Context) (CountReviewsRow, error)
	// Запускает ON DELETE-политики детей: CASCADE удалит заказы, SET NULL обнулит
	// ссылку в отзывах.
	DeleteCustomer(ctx context.Context, id int64) error
	// Дефолтный FK fk_orderitem → fk_drink (NO ACTION): пока есть ссылка → 23503.
	DeleteDrink(ctx context.Context, id int64) error
	InsertCustomer(ctx context.Context, name string) (int64, error)
	InsertDrink(ctx context.Context, name string) (int64, error)
	// customer_id с несуществующим значением → SQLSTATE 23503 (FK не даёт повиснуть).
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error
	InsertReview(ctx context.Context, arg InsertReviewParams) error
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — ссылочная целостность: FK не даёт сослаться на несуществующего
	// родителя (23503), а ON DELETE решает судьбу детей при удалении родителя:
	// CASCADE — удалить, SET NULL — обнулить ссылку, дефолт NO ACTION — запретить.
	// CASCADE в TRUNCATE — это про сами таблицы (очистить и связанные), не путать с
	// ON DELETE CASCADE внешнего ключа.
	ResetFK(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
