// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const insertAlways = `-- name: InsertAlways :one
INSERT INTO id_always (label) VALUES ($1)
RETURNING id, (created_at IS NOT NULL)::boolean AS created_at_filled
`

type InsertAlwaysRow struct {
	ID              int64 `json:"id"`
	CreatedAtFilled bool  `json:"created_at_filled"`
}

// id не передаём — его присваивает БД из IDENTITY; created_at не передаём — его
// подставляет DEFAULT now(). Возвращаем id и факт, что DEFAULT сработал.
func (q *Queries) InsertAlways(ctx context.Context, label string) (InsertAlwaysRow, error) {
	row := q.db.QueryRow(ctx, insertAlways, label)
	var i InsertAlwaysRow
	err := row.Scan(&i.ID, &i.CreatedAtFilled)
	return i, err
}

const insertAlwaysExplicitID = `-- name: InsertAlwaysExplicitID :exec
INSERT INTO id_always (id, label) VALUES ($1, $2)
`

type InsertAlwaysExplicitIDParams struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
}

// Попытка задать id вручную в GENERATED ALWAYS — БД отклонит (SQLSTATE 428C9):
// владелец колонки — база, а не приложение.
func (q *Queries) InsertAlwaysExplicitID(ctx context.Context, arg InsertAlwaysExplicitIDParams) error {
	_, err := q.db.Exec(ctx, insertAlwaysExplicitID, arg.ID, arg.Label)
	return err
}

const insertByDefaultExplicitID = `-- name: InsertByDefaultExplicitID :one
INSERT INTO id_by_default (id, label) VALUES ($1, $2)
RETURNING id
`

type InsertByDefaultExplicitIDParams struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
}

// В GENERATED BY DEFAULT (как serial) явный id принимается. Счётчик IDENTITY при
// этом НЕ двигается — отсюда классический рассинхрон serial (см. README).
func (q *Queries) InsertByDefaultExplicitID(ctx context.Context, arg InsertByDefaultExplicitIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertByDefaultExplicitID, arg.ID, arg.Label)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const resetIdAlways = `-- name: ResetIdAlways :exec

TRUNCATE id_always RESTART IDENTITY
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — два режима IDENTITY и обычный DEFAULT. GENERATED ALWAYS отдаёт
// владение ключом базе (приложение не может вписать свой id); GENERATED BY
// DEFAULT ведёт себя как serial — примет и явный id. Демонстрируем оба и
// обычный DEFAULT (now()), значение которого подставляется при пропуске.
// Перед демо обнуляем таблицу и счётчик IDENTITY — вывод воспроизводим
// (id всегда стартуют с 1) независимо от числа прогонов.
func (q *Queries) ResetIdAlways(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetIdAlways)
	return err
}

const resetIdByDefault = `-- name: ResetIdByDefault :exec
TRUNCATE id_by_default RESTART IDENTITY
`

func (q *Queries) ResetIdByDefault(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetIdByDefault)
	return err
}
