// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// id не передаём — его присваивает БД из IDENTITY; created_at не передаём — его
	// подставляет DEFAULT now(). Возвращаем id и факт, что DEFAULT сработал.
	InsertAlways(ctx context.Context, label string) (InsertAlwaysRow, error)
	// Попытка задать id вручную в GENERATED ALWAYS — БД отклонит (SQLSTATE 428C9):
	// владелец колонки — база, а не приложение.
	InsertAlwaysExplicitID(ctx context.Context, arg InsertAlwaysExplicitIDParams) error
	// В GENERATED BY DEFAULT (как serial) явный id принимается. Счётчик IDENTITY при
	// этом НЕ двигается — отсюда классический рассинхрон serial (см. README).
	InsertByDefaultExplicitID(ctx context.Context, arg InsertByDefaultExplicitIDParams) (int64, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — два режима IDENTITY и обычный DEFAULT. GENERATED ALWAYS отдаёт
	// владение ключом базе (приложение не может вписать свой id); GENERATED BY
	// DEFAULT ведёт себя как serial — примет и явный id. Демонстрируем оба и
	// обычный DEFAULT (now()), значение которого подставляется при пропуске.
	// Перед демо обнуляем таблицу и счётчик IDENTITY — вывод воспроизводим
	// (id всегда стартуют с 1) независимо от числа прогонов.
	ResetIdAlways(ctx context.Context) error
	ResetIdByDefault(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
