// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Перепись мира Brew: сколько строк лежит в каждой таблице канона после seed.
	// ord фиксирует порядок (UNION ALL без ORDER BY его не гарантирует).
	BrewWorld(ctx context.Context) ([]BrewWorldRow, error)
	// query.sql — протагонист урока. SQL пишем руками; `make gen` (sqlc generate)
	// генерирует типизированный pgx-код в internal/db/. Имя после `-- name:` →
	// метод на *db.Queries; суффикс (:one / :many) — форма результата.
	// Первый контакт: какая версия Postgres отвечает на том конце сокета.
	ServerVersion(ctx context.Context) (string, error)
}

var _ Querier = (*Queries)(nil)
