// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const brewWorld = `-- name: BrewWorld :many
SELECT entity, n FROM (
    SELECT 1 AS ord, 'customers'::text     AS entity, count(*) AS n FROM customers
    UNION ALL SELECT 2, 'drinks',               count(*) FROM drinks
    UNION ALL SELECT 3, 'articles',             count(*) FROM articles
    UNION ALL SELECT 4, 'orders',               count(*) FROM orders
    UNION ALL SELECT 5, 'outbox',               count(*) FROM outbox
    UNION ALL SELECT 6, 'processed_outbox_ids', count(*) FROM processed_outbox_ids
    UNION ALL SELECT 7, 'shops',                count(*) FROM shops
    UNION ALL SELECT 8, 'order_items',          count(*) FROM order_items
    UNION ALL SELECT 9, 'inventory',            count(*) FROM inventory
) w
ORDER BY ord
`

type BrewWorldRow struct {
	Entity string `json:"entity"`
	N      int64  `json:"n"`
}

// Перепись мира Brew: сколько строк лежит в каждой таблице канона после seed.
// ord фиксирует порядок (UNION ALL без ORDER BY его не гарантирует).
func (q *Queries) BrewWorld(ctx context.Context) ([]BrewWorldRow, error) {
	rows, err := q.db.Query(ctx, brewWorld)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrewWorldRow{}
	for rows.Next() {
		var i BrewWorldRow
		if err := rows.Scan(&i.Entity, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serverVersion = `-- name: ServerVersion :one

SELECT version()
`

// query.sql — протагонист урока. SQL пишем руками; `make gen` (sqlc generate)
// генерирует типизированный pgx-код в internal/db/. Имя после `-- name:` →
// метод на *db.Queries; суффикс (:one / :many) — форма результата.
// Первый контакт: какая версия Postgres отвечает на том конце сокета.
func (q *Queries) ServerVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, serverVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}
