// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const countUniqDefault = `-- name: CountUniqDefault :one
SELECT count(*)::bigint AS n FROM uniq_default
`

func (q *Queries) CountUniqDefault(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUniqDefault)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countUniqNND = `-- name: CountUniqNND :one
SELECT count(*)::bigint AS n FROM uniq_nnd
`

func (q *Queries) CountUniqNND(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUniqNND)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const insertCheckDrink = `-- name: InsertCheckDrink :exec
INSERT INTO check_drink (name, price, size) VALUES ($1, $2, $3)
`

type InsertCheckDrinkParams struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
	Size  string `json:"size"`
}

// price > 0 и size IN (...) — нарушение любого CHECK → SQLSTATE 23514.
func (q *Queries) InsertCheckDrink(ctx context.Context, arg InsertCheckDrinkParams) error {
	_, err := q.db.Exec(ctx, insertCheckDrink, arg.Name, arg.Price, arg.Size)
	return err
}

const insertUniqDefaultA = `-- name: InsertUniqDefaultA :exec
INSERT INTO uniq_default (slot) VALUES ('A')
`

// Непустое значение: второй такой же → SQLSTATE 23505 (unique_violation).
func (q *Queries) InsertUniqDefaultA(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertUniqDefaultA)
	return err
}

const insertUniqDefaultNull = `-- name: InsertUniqDefaultNull :exec
INSERT INTO uniq_default (slot) VALUES (NULL)
`

// NULL в UNIQUE-колонку: по умолчанию проходит сколько угодно раз (NULL ≠ NULL).
func (q *Queries) InsertUniqDefaultNull(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertUniqDefaultNull)
	return err
}

const insertUniqNNDNull = `-- name: InsertUniqNNDNull :exec
INSERT INTO uniq_nnd (slot) VALUES (NULL)
`

// NULL под NULLS NOT DISTINCT: второй NULL уже дубль → SQLSTATE 23505.
func (q *Queries) InsertUniqNNDNull(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertUniqNNDNull)
	return err
}

const resetCheckDrink = `-- name: ResetCheckDrink :exec
TRUNCATE check_drink RESTART IDENTITY
`

func (q *Queries) ResetCheckDrink(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetCheckDrink)
	return err
}

const resetUniqDefault = `-- name: ResetUniqDefault :exec

TRUNCATE uniq_default RESTART IDENTITY
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — UNIQUE и CHECK. Ключевой сюрприз UNIQUE: по умолчанию NULL ≠ NULL,
// поэтому несколько NULL проходят; NULLS NOT DISTINCT (PG15) это меняет. CHECK
// проверяет значение и отбивает нарушителя с SQLSTATE 23514.
func (q *Queries) ResetUniqDefault(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetUniqDefault)
	return err
}

const resetUniqNND = `-- name: ResetUniqNND :exec
TRUNCATE uniq_nnd RESTART IDENTITY
`

func (q *Queries) ResetUniqNND(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetUniqNND)
	return err
}
