// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountUniqDefault(ctx context.Context) (int64, error)
	CountUniqNND(ctx context.Context) (int64, error)
	// price > 0 и size IN (...) — нарушение любого CHECK → SQLSTATE 23514.
	InsertCheckDrink(ctx context.Context, arg InsertCheckDrinkParams) error
	// Непустое значение: второй такой же → SQLSTATE 23505 (unique_violation).
	InsertUniqDefaultA(ctx context.Context) error
	// NULL в UNIQUE-колонку: по умолчанию проходит сколько угодно раз (NULL ≠ NULL).
	InsertUniqDefaultNull(ctx context.Context) error
	// NULL под NULLS NOT DISTINCT: второй NULL уже дубль → SQLSTATE 23505.
	InsertUniqNNDNull(ctx context.Context) error
	ResetCheckDrink(ctx context.Context) error
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — UNIQUE и CHECK. Ключевой сюрприз UNIQUE: по умолчанию NULL ≠ NULL,
	// поэтому несколько NULL проходят; NULLS NOT DISTINCT (PG15) это меняет. CHECK
	// проверяет значение и отбивает нарушителя с SQLSTATE 23514.
	ResetUniqDefault(ctx context.Context) error
	ResetUniqNND(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
