// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Выдаём карту: передаём только customer_id и card_no. id присвоит БД (IDENTITY),
	// points и created_at подставит DEFAULT. RETURNING возвращает их в том же
	// round-trip — без отдельного SELECT за сгенерированным id.
	IssueCard(ctx context.Context, arg IssueCardParams) (IssueCardRow, error)
	// Многострочный INSERT: одна команда вставляет сразу несколько карт, и RETURNING
	// отдаёт id каждой — по строке на вставленную карту (форма :many). Так RETURNING
	// работает и для одной строки, и для многих. (Для вставки переменного числа
	// строк из Go-среза берут `unnest($1::bigint[])`, а для массовой загрузки —
	// COPY; см. заборчик и forward-ссылку на 09-01.)
	IssueCardsBulk(ctx context.Context, arg IssueCardsBulkParams) ([]IssueCardsBulkRow, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — INSERT ... RETURNING. Главный вывод: значения, которые присваивает
	// сервер (сгенерированный id, колонки по DEFAULT), приезжают обратно тем же
	// запросом — второй SELECT не нужен. И это работает не только для одной строки:
	// bulk-INSERT через unnest тоже умеет RETURNING.
	// Перед демо обнуляем таблицу и счётчик IDENTITY — id всегда стартуют с 1,
	// вывод воспроизводим независимо от числа прогонов.
	TruncateCards(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
