// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const issueCard = `-- name: IssueCard :one
INSERT INTO loyalty_cards (customer_id, card_no)
VALUES ($1, $2)
RETURNING id, points, (created_at IS NOT NULL)::boolean AS created_set
`

type IssueCardParams struct {
	CustomerID int64  `json:"customer_id"`
	CardNo     string `json:"card_no"`
}

type IssueCardRow struct {
	ID         int64 `json:"id"`
	Points     int32 `json:"points"`
	CreatedSet bool  `json:"created_set"`
}

// Выдаём карту: передаём только customer_id и card_no. id присвоит БД (IDENTITY),
// points и created_at подставит DEFAULT. RETURNING возвращает их в том же
// round-trip — без отдельного SELECT за сгенерированным id.
func (q *Queries) IssueCard(ctx context.Context, arg IssueCardParams) (IssueCardRow, error) {
	row := q.db.QueryRow(ctx, issueCard, arg.CustomerID, arg.CardNo)
	var i IssueCardRow
	err := row.Scan(&i.ID, &i.Points, &i.CreatedSet)
	return i, err
}

const issueCardsBulk = `-- name: IssueCardsBulk :many
INSERT INTO loyalty_cards (customer_id, card_no)
VALUES ($1, $2),
       ($3, $4)
RETURNING id, card_no
`

type IssueCardsBulkParams struct {
	CustA int64  `json:"cust_a"`
	CardA string `json:"card_a"`
	CustB int64  `json:"cust_b"`
	CardB string `json:"card_b"`
}

type IssueCardsBulkRow struct {
	ID     int64  `json:"id"`
	CardNo string `json:"card_no"`
}

// Многострочный INSERT: одна команда вставляет сразу несколько карт, и RETURNING
// отдаёт id каждой — по строке на вставленную карту (форма :many). Так RETURNING
// работает и для одной строки, и для многих. (Для вставки переменного числа
// строк из Go-среза берут `unnest($1::bigint[])`, а для массовой загрузки —
// COPY; см. заборчик и forward-ссылку на 09-01.)
func (q *Queries) IssueCardsBulk(ctx context.Context, arg IssueCardsBulkParams) ([]IssueCardsBulkRow, error) {
	rows, err := q.db.Query(ctx, issueCardsBulk,
		arg.CustA,
		arg.CardA,
		arg.CustB,
		arg.CardB,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueCardsBulkRow{}
	for rows.Next() {
		var i IssueCardsBulkRow
		if err := rows.Scan(&i.ID, &i.CardNo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateCards = `-- name: TruncateCards :exec

TRUNCATE loyalty_cards RESTART IDENTITY
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — INSERT ... RETURNING. Главный вывод: значения, которые присваивает
// сервер (сгенерированный id, колонки по DEFAULT), приезжают обратно тем же
// запросом — второй SELECT не нужен. И это работает не только для одной строки:
// bulk-INSERT через unnest тоже умеет RETURNING.
// Перед демо обнуляем таблицу и счётчик IDENTITY — id всегда стартуют с 1,
// вывод воспроизводим независимо от числа прогонов.
func (q *Queries) TruncateCards(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateCards)
	return err
}
