// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM price_lab WHERE category = $1
`

// DELETE с условием. :execrows отдаёт число удалённых строк — тоже масштаб.
func (q *Queries) DeleteCategory(ctx context.Context, category string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, category)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPriceLab = `-- name: ListPriceLab :many
SELECT id, name, category, price FROM price_lab ORDER BY id
`

func (q *Queries) ListPriceLab(ctx context.Context) ([]PriceLab, error) {
	rows, err := q.db.Query(ctx, listPriceLab)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceLab{}
	for rows.Next() {
		var i PriceLab
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raiseAll = `-- name: RaiseAll :execrows
UPDATE price_lab
SET price = price + $1
`

// «Забыл WHERE»: UPDATE без условия задевает ВСЮ таблицу. Форма :execrows
// возвращает число затронутых строк — это и есть масштаб, который надо увидеть
// ДО коммита (в демо мы исполняем это внутри транзакции и откатываем).
func (q *Queries) RaiseAll(ctx context.Context, delta int64) (int64, error) {
	result, err := q.db.Exec(ctx, raiseAll, delta)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const raiseCategory = `-- name: RaiseCategory :many
UPDATE price_lab
SET price = price + $1
WHERE category = $2
RETURNING id, name, price
`

type RaiseCategoryParams struct {
	Delta    int64  `json:"delta"`
	Category string `json:"category"`
}

type RaiseCategoryRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

// Целевой UPDATE: меняем цену только в одной категории. RETURNING возвращает
// ровно затронутые строки — видно, что задето именно то, что хотели.
func (q *Queries) RaiseCategory(ctx context.Context, arg RaiseCategoryParams) ([]RaiseCategoryRow, error) {
	rows, err := q.db.Query(ctx, raiseCategory, arg.Delta, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RaiseCategoryRow{}
	for rows.Next() {
		var i RaiseCategoryRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedPriceRow = `-- name: SeedPriceRow :exec
INSERT INTO price_lab (name, category, price) VALUES ($1, $2, $3)
`

type SeedPriceRowParams struct {
	Name     string `json:"name"`
	Category string `json:"category"`
	Price    int64  `json:"price"`
}

func (q *Queries) SeedPriceRow(ctx context.Context, arg SeedPriceRowParams) error {
	_, err := q.db.Exec(ctx, seedPriceRow, arg.Name, arg.Category, arg.Price)
	return err
}

const truncatePriceLab = `-- name: TruncatePriceLab :exec

TRUNCATE price_lab RESTART IDENTITY
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — менять и удалять строки безопасно. Два инструмента «увидеть масштаб»:
// RETURNING (какие именно строки задело) и :execrows (сколько строк задело).
// И главный приём безопасности: рискованную запись делаем внутри транзакции —
// забытый WHERE тогда откатывается, а не превращается в инцидент на проде.
// Перед демо обнуляем таблицу и счётчик IDENTITY — id всегда 1..5, вывод
// воспроизводим независимо от числа прогонов.
func (q *Queries) TruncatePriceLab(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncatePriceLab)
	return err
}
