// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// DELETE с условием. :execrows отдаёт число удалённых строк — тоже масштаб.
	DeleteCategory(ctx context.Context, category string) (int64, error)
	ListPriceLab(ctx context.Context) ([]PriceLab, error)
	// «Забыл WHERE»: UPDATE без условия задевает ВСЮ таблицу. Форма :execrows
	// возвращает число затронутых строк — это и есть масштаб, который надо увидеть
	// ДО коммита (в демо мы исполняем это внутри транзакции и откатываем).
	RaiseAll(ctx context.Context, delta int64) (int64, error)
	// Целевой UPDATE: меняем цену только в одной категории. RETURNING возвращает
	// ровно затронутые строки — видно, что задето именно то, что хотели.
	RaiseCategory(ctx context.Context, arg RaiseCategoryParams) ([]RaiseCategoryRow, error)
	SeedPriceRow(ctx context.Context, arg SeedPriceRowParams) error
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — менять и удалять строки безопасно. Два инструмента «увидеть масштаб»:
	// RETURNING (какие именно строки задело) и :execrows (сколько строк задело).
	// И главный приём безопасности: рискованную запись делаем внутри транзакции —
	// забытый WHERE тогда откатывается, а не превращается в инцидент на проде.
	// Перед демо обнуляем таблицу и счётчик IDENTITY — id всегда 1..5, вывод
	// воспроизводим независимо от числа прогонов.
	TruncatePriceLab(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
