// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const countDrinksByCategory = `-- name: CountDrinksByCategory :one
SELECT count(*)
FROM drinks
WHERE category = $1
`

// :one со скаляром → int64. Тот же $1 (category), но результат — одно число.
func (q *Queries) CountDrinksByCategory(ctx context.Context, category string) (int64, error) {
	row := q.db.QueryRow(ctx, countDrinksByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDrinkBySKU = `-- name: GetDrinkBySKU :one
SELECT id, sku, name, category, base_price
FROM drinks
WHERE sku = $1
`

type GetDrinkBySKURow struct {
	ID        int64  `json:"id"`
	Sku       string `json:"sku"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	BasePrice int64  `json:"base_price"`
}

// :one → одна строка (pgx вернёт ErrNoRows, если совпадения нет). $1 = sku.
func (q *Queries) GetDrinkBySKU(ctx context.Context, sku string) (GetDrinkBySKURow, error) {
	row := q.db.QueryRow(ctx, getDrinkBySKU, sku)
	var i GetDrinkBySKURow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.BasePrice,
	)
	return i, err
}

const listDrinksByCategory = `-- name: ListDrinksByCategory :many

SELECT id, sku, name, category, base_price
FROM drinks
WHERE category = $1
ORDER BY id
`

type ListDrinksByCategoryRow struct {
	ID        int64  `json:"id"`
	Sku       string `json:"sku"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	BasePrice int64  `json:"base_price"`
}

// query.sql — протагонист урока. SQL пишем руками; `make gen` (sqlc generate)
// генерирует типизированный pgx-код в internal/db/. Имя после `-- name:` →
// метод на *db.Queries; суффикс (:one / :many / :exec) — форма результата.
//
// Главное здесь — параметр $1. В 00-03 мы передавали его в pool.Query и сами
// разбирали строки через rows.Scan. Тут sqlc выводит ИМЯ и ТИП параметра из
// схемы: для `WHERE category = $1` он видит, что drinks.category — text, и
// генерирует метод с аргументом `category string`. Перепутать тип или порядок
// колонок становится ошибкой компиляции, а не молчаливым багом в рантайме.
// :many → []ListDrinksByCategoryRow. $1 (category) типизирован из схемы как string.
func (q *Queries) ListDrinksByCategory(ctx context.Context, category string) ([]ListDrinksByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listDrinksByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrinksByCategoryRow{}
	for rows.Next() {
		var i ListDrinksByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.BasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
