// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// :one со скаляром → int64. Тот же $1 (category), но результат — одно число.
	CountDrinksByCategory(ctx context.Context, category string) (int64, error)
	// :one → одна строка (pgx вернёт ErrNoRows, если совпадения нет). $1 = sku.
	GetDrinkBySKU(ctx context.Context, sku string) (GetDrinkBySKURow, error)
	// query.sql — протагонист урока. SQL пишем руками; `make gen` (sqlc generate)
	// генерирует типизированный pgx-код в internal/db/. Имя после `-- name:` →
	// метод на *db.Queries; суффикс (:one / :many / :exec) — форма результата.
	//
	// Главное здесь — параметр $1. В 00-03 мы передавали его в pool.Query и сами
	// разбирали строки через rows.Scan. Тут sqlc выводит ИМЯ и ТИП параметра из
	// схемы: для `WHERE category = $1` он видит, что drinks.category — text, и
	// генерирует метод с аргументом `category string`. Перепутать тип или порядок
	// колонок становится ошибкой компиляции, а не молчаливым багом в рантайме.
	// :many → []ListDrinksByCategoryRow. $1 (category) типизирован из схемы как string.
	ListDrinksByCategory(ctx context.Context, category string) ([]ListDrinksByCategoryRow, error)
}

var _ Querier = (*Queries)(nil)
