// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Массив, оператор = ANY: проверка принадлежности одного значения. Параметр
	// $1 sqlc типизирует из схемы (tags — text[] → элемент text → Go string).
	ArrayHasTag(ctx context.Context, tag string) ([]string, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — массив против таблицы-связки. Один и тот же вопрос («напитки с тегом
	// coffee») задаём обеим моделям и видим, что результат совпадает, а вот цена
	// разных вопросов разная: containment по массиву — один оператор, а частота
	// тегов тривиальна на junction (GROUP BY) и неуклюжа на массиве (нужен unnest).
	// Массив, оператор @> («содержит»): теги напитка включают coffee. На большой
	// таблице это ускоряет GIN-индекс по tags (см. 06-05).
	ArrayTaggedCoffee(ctx context.Context) ([]string, error)
	// Та же выборка на нормализованной модели — обычный фильтр по строке-связке.
	// Результат совпадает с ArrayTaggedCoffee: модели эквивалентны по данным.
	JunctionTaggedCoffee(ctx context.Context) ([]string, error)
	// Козырь нормализации: «сколько напитков у каждого тега» — это просто GROUP BY.
	// На массиве пришлось бы разворачивать unnest(tags) и группировать — лишний шаг.
	TagPopularity(ctx context.Context) ([]TagPopularityRow, error)
	// Мост между моделями: array_agg сворачивает строки-связки обратно в массив.
	// ORDER BY внутри агрегата → стабильный порядок элементов. ::text[] → Go []string.
	TagsFromJunction(ctx context.Context) ([]TagsFromJunctionRow, error)
}

var _ Querier = (*Queries)(nil)
