// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const arrayHasTag = `-- name: ArrayHasTag :many
SELECT drink_sku
FROM drink_tags_arr
WHERE $1::text = ANY(tags)
ORDER BY drink_sku
`

// Массив, оператор = ANY: проверка принадлежности одного значения. Параметр
// $1 sqlc типизирует из схемы (tags — text[] → элемент text → Go string).
func (q *Queries) ArrayHasTag(ctx context.Context, tag string) ([]string, error) {
	rows, err := q.db.Query(ctx, arrayHasTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var drink_sku string
		if err := rows.Scan(&drink_sku); err != nil {
			return nil, err
		}
		items = append(items, drink_sku)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const arrayTaggedCoffee = `-- name: ArrayTaggedCoffee :many

SELECT drink_sku
FROM drink_tags_arr
WHERE tags @> ARRAY['coffee']
ORDER BY drink_sku
`

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — массив против таблицы-связки. Один и тот же вопрос («напитки с тегом
// coffee») задаём обеим моделям и видим, что результат совпадает, а вот цена
// разных вопросов разная: containment по массиву — один оператор, а частота
// тегов тривиальна на junction (GROUP BY) и неуклюжа на массиве (нужен unnest).
// Массив, оператор @> («содержит»): теги напитка включают coffee. На большой
// таблице это ускоряет GIN-индекс по tags (см. 06-05).
func (q *Queries) ArrayTaggedCoffee(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, arrayTaggedCoffee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var drink_sku string
		if err := rows.Scan(&drink_sku); err != nil {
			return nil, err
		}
		items = append(items, drink_sku)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const junctionTaggedCoffee = `-- name: JunctionTaggedCoffee :many
SELECT drink_sku
FROM drink_tags
WHERE tag = 'coffee'
ORDER BY drink_sku
`

// Та же выборка на нормализованной модели — обычный фильтр по строке-связке.
// Результат совпадает с ArrayTaggedCoffee: модели эквивалентны по данным.
func (q *Queries) JunctionTaggedCoffee(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, junctionTaggedCoffee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var drink_sku string
		if err := rows.Scan(&drink_sku); err != nil {
			return nil, err
		}
		items = append(items, drink_sku)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagPopularity = `-- name: TagPopularity :many
SELECT tag, count(*)::bigint AS used
FROM drink_tags
GROUP BY tag
ORDER BY used DESC, tag
`

type TagPopularityRow struct {
	Tag  string `json:"tag"`
	Used int64  `json:"used"`
}

// Козырь нормализации: «сколько напитков у каждого тега» — это просто GROUP BY.
// На массиве пришлось бы разворачивать unnest(tags) и группировать — лишний шаг.
func (q *Queries) TagPopularity(ctx context.Context) ([]TagPopularityRow, error) {
	rows, err := q.db.Query(ctx, tagPopularity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagPopularityRow{}
	for rows.Next() {
		var i TagPopularityRow
		if err := rows.Scan(&i.Tag, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagsFromJunction = `-- name: TagsFromJunction :many
SELECT drink_sku, array_agg(tag ORDER BY tag)::text[] AS tags
FROM drink_tags
GROUP BY drink_sku
ORDER BY drink_sku
`

type TagsFromJunctionRow struct {
	DrinkSku string   `json:"drink_sku"`
	Tags     []string `json:"tags"`
}

// Мост между моделями: array_agg сворачивает строки-связки обратно в массив.
// ORDER BY внутри агрегата → стабильный порядок элементов. ::text[] → Go []string.
func (q *Queries) TagsFromJunction(ctx context.Context) ([]TagsFromJunctionRow, error) {
	rows, err := q.db.Query(ctx, tagsFromJunction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagsFromJunctionRow{}
	for rows.Next() {
		var i TagsFromJunctionRow
		if err := rows.Scan(&i.DrinkSku, &i.Tags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
