// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Сколько напитков в меню Brew — sanity-check, что seed-данные накатились.
	CountDrinks(ctx context.Context) (int64, error)
	// Меню Brew: сервер хранит строки, мы запрашиваем их по своему запросу.
	// base_price — в минорных единицах (центах), BIGINT.
	ListDrinks(ctx context.Context) ([]ListDrinksRow, error)
	// query.sql — протагонист урока. SQL пишем руками; `make gen` (sqlc generate)
	// генерирует типизированный pgx-код в internal/db/. Имя после `-- name:` →
	// метод на *db.Queries; суффикс (:one / :many) — форма результата.
	// Первый запрос к серверу: какая версия Postgres отвечает на том конце сокета.
	ServerVersion(ctx context.Context) (string, error)
}

var _ Querier = (*Queries)(nil)
