// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Правильный способ: NOT EXISTS. Он спрашивает «нет ли совпадающей строки», и
	// NULL в unavailable никого не исключает (NULL ни с чем не совпадает). Итог — 4
	// (пять напитков минус колд брю #4).
	CountAvailableNotExists(ctx context.Context) (int64, error)
	// Ловушка: id NOT IN (4, NULL). Для любого id это NOT (id=4 OR id=NULL) =
	// NOT (… OR NULL). Если id<>4, получается NOT (NULL) = NULL — строка НЕ проходит
	// фильтр. Итог — 0, хотя доступных напитков явно больше.
	CountAvailableNotIn(ctx context.Context) (int64, error)
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — трезвая семантика NULL (расплата за тизер из 01-02). В Postgres NULL —
	// это «неизвестно», и логика трёхзначная: сравнение с NULL даёт не true/false, а
	// NULL (UNKNOWN). Отсюда знаменитая ловушка NOT IN со списком, где есть NULL: он
	// молча возвращает «ничего». Плюс три инструмента безопасной работы с NULL:
	// COALESCE, NULLIF, IS DISTINCT FROM.
	// Четыре факта на литералах. Каждое выражение детерминированно и не-NULL (внешний
	// IS NULL / IS NOT DISTINCT / COALESCE сворачивает результат к bool/int).
	NullLogic(ctx context.Context) (NullLogicRow, error)
	// Список недоступных: напиток #4 (колд брю) и затесавшийся NULL. Этого одного
	// NULL достаточно, чтобы сломать NOT IN ниже.
	SeedUnavailable(ctx context.Context) error
	// первое не-NULL
	TruncateUnavailable(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
