// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const countAvailableNotExists = `-- name: CountAvailableNotExists :one
SELECT count(*) FROM drinks d
WHERE NOT EXISTS (
    SELECT 1 FROM unavailable u WHERE u.drink_id = d.id
)
`

// Правильный способ: NOT EXISTS. Он спрашивает «нет ли совпадающей строки», и
// NULL в unavailable никого не исключает (NULL ни с чем не совпадает). Итог — 4
// (пять напитков минус колд брю #4).
func (q *Queries) CountAvailableNotExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableNotExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAvailableNotIn = `-- name: CountAvailableNotIn :one
SELECT count(*) FROM drinks
WHERE id NOT IN (SELECT drink_id FROM unavailable)
`

// Ловушка: id NOT IN (4, NULL). Для любого id это NOT (id=4 OR id=NULL) =
// NOT (… OR NULL). Если id<>4, получается NOT (NULL) = NULL — строка НЕ проходит
// фильтр. Итог — 0, хотя доступных напитков явно больше.
func (q *Queries) CountAvailableNotIn(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableNotIn)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const nullLogic = `-- name: NullLogic :one

SELECT
    ((NULL = NULL) IS NULL)                  AS eq_is_null,         -- (=) с NULL → NULL, не true
    (NULL IS NOT DISTINCT FROM NULL)         AS is_not_distinct,    -- NULL-безопасное равенство
    (NULLIF(100, 100) IS NULL)               AS nullif_eq_is_null,  -- NULLIF(a,a) → NULL
    COALESCE(NULL::int, NULL, 42)            AS coalesce_val
`

type NullLogicRow struct {
	EqIsNull       interface{} `json:"eq_is_null"`
	IsNotDistinct  bool        `json:"is_not_distinct"`
	NullifEqIsNull interface{} `json:"nullif_eq_is_null"`
	CoalesceVal    interface{} `json:"coalesce_val"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — трезвая семантика NULL (расплата за тизер из 01-02). В Postgres NULL —
// это «неизвестно», и логика трёхзначная: сравнение с NULL даёт не true/false, а
// NULL (UNKNOWN). Отсюда знаменитая ловушка NOT IN со списком, где есть NULL: он
// молча возвращает «ничего». Плюс три инструмента безопасной работы с NULL:
// COALESCE, NULLIF, IS DISTINCT FROM.
// Четыре факта на литералах. Каждое выражение детерминированно и не-NULL (внешний
// IS NULL / IS NOT DISTINCT / COALESCE сворачивает результат к bool/int).
func (q *Queries) NullLogic(ctx context.Context) (NullLogicRow, error) {
	row := q.db.QueryRow(ctx, nullLogic)
	var i NullLogicRow
	err := row.Scan(
		&i.EqIsNull,
		&i.IsNotDistinct,
		&i.NullifEqIsNull,
		&i.CoalesceVal,
	)
	return i, err
}

const seedUnavailable = `-- name: SeedUnavailable :exec
INSERT INTO unavailable (drink_id) VALUES (4), (NULL)
`

// Список недоступных: напиток #4 (колд брю) и затесавшийся NULL. Этого одного
// NULL достаточно, чтобы сломать NOT IN ниже.
func (q *Queries) SeedUnavailable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedUnavailable)
	return err
}

const truncateUnavailable = `-- name: TruncateUnavailable :exec

TRUNCATE unavailable
`

// первое не-NULL
func (q *Queries) TruncateUnavailable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateUnavailable)
	return err
}
