// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — четыре вида JOIN. Сводим клиентов и их заказы и смотрим, какие строки
	// каждый JOIN сохраняет, а какие выкидывает. customers.id — BIGINT, а
	// orders.customer_id — TEXT (так в каноне Brew), поэтому связываем их с явным
	// приведением c.id::text = o.customer_id.
	// INNER JOIN: только пары, где совпадение есть с ОБЕИХ сторон. Клиент без
	// заказов (Карина) сюда не попадёт — у неё нет совпадающей строки в orders.
	InnerCustomersOrders(ctx context.Context) ([]InnerCustomersOrdersRow, error)
	// LEFT JOIN: сохраняем ВСЕ строки левой таблицы (customers), даже без пары
	// справа. У Карины заказов нет → order_id и status придут NULL (sqlc типизирует
	// их как nullable). Это классический «все клиенты и их заказы, если есть».
	LeftCustomersOrders(ctx context.Context) ([]LeftCustomersOrdersRow, error)
	// FULL JOIN: сохраняем несовпавшие строки С ОБЕИХ сторон. Напиток только в зале
	// → storage_qty NULL; только на складе → floor_qty NULL; посчитан в обоих →
	// обе цены. Имя берём из drinks по COALESCE ключа (ключ есть хотя бы с одной
	// стороны). Это типичная сверка двух источников: «покажи всё, что есть хоть
	// где-то, и подсветь расхождения».
	ReconcileFull(ctx context.Context) ([]ReconcileFullRow, error)
	// RIGHT JOIN: зеркало LEFT — сохраняем все строки ПРАВОЙ таблицы (customers).
	// Тот же результат, что у LEFT выше, просто таблицы переставлены местами. RIGHT
	// в коде встречается редко именно потому, что любой RIGHT можно записать как
	// LEFT, поменяв порядок таблиц, — и так читается естественнее.
	RightOrdersCustomers(ctx context.Context) ([]RightOrdersCustomersRow, error)
	// Зал посчитал напитки {1, 2}.
	SeedFloor(ctx context.Context) error
	// Склад посчитал {2, 4}. Пересечение (2) совпадёт, а 1 и 4 останутся каждый в
	// своём листе — ровно те несовпадения, что покажет FULL JOIN.
	SeedStorage(ctx context.Context) error
	// Перед демо обнуляем оба листа пересчёта — вывод воспроизводим при любом числе
	// прогонов.
	TruncateCounts(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
