// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const innerCustomersOrders = `-- name: InnerCustomersOrders :many

SELECT c.name AS customer, o.id AS order_id, o.status
FROM customers c
JOIN orders o ON o.customer_id = c.id::text
ORDER BY c.id, o.id
`

type InnerCustomersOrdersRow struct {
	Customer string `json:"customer"`
	OrderID  int64  `json:"order_id"`
	Status   string `json:"status"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — четыре вида JOIN. Сводим клиентов и их заказы и смотрим, какие строки
// каждый JOIN сохраняет, а какие выкидывает. customers.id — BIGINT, а
// orders.customer_id — TEXT (так в каноне Brew), поэтому связываем их с явным
// приведением c.id::text = o.customer_id.
// INNER JOIN: только пары, где совпадение есть с ОБЕИХ сторон. Клиент без
// заказов (Карина) сюда не попадёт — у неё нет совпадающей строки в orders.
func (q *Queries) InnerCustomersOrders(ctx context.Context) ([]InnerCustomersOrdersRow, error) {
	rows, err := q.db.Query(ctx, innerCustomersOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InnerCustomersOrdersRow{}
	for rows.Next() {
		var i InnerCustomersOrdersRow
		if err := rows.Scan(&i.Customer, &i.OrderID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leftCustomersOrders = `-- name: LeftCustomersOrders :many
SELECT c.name AS customer, o.id AS order_id, o.status
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id::text
ORDER BY c.id, o.id
`

type LeftCustomersOrdersRow struct {
	Customer string      `json:"customer"`
	OrderID  pgtype.Int8 `json:"order_id"`
	Status   pgtype.Text `json:"status"`
}

// LEFT JOIN: сохраняем ВСЕ строки левой таблицы (customers), даже без пары
// справа. У Карины заказов нет → order_id и status придут NULL (sqlc типизирует
// их как nullable). Это классический «все клиенты и их заказы, если есть».
func (q *Queries) LeftCustomersOrders(ctx context.Context) ([]LeftCustomersOrdersRow, error) {
	rows, err := q.db.Query(ctx, leftCustomersOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeftCustomersOrdersRow{}
	for rows.Next() {
		var i LeftCustomersOrdersRow
		if err := rows.Scan(&i.Customer, &i.OrderID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileFull = `-- name: ReconcileFull :many
SELECT d.name AS drink, f.qty AS floor_qty, s.qty AS storage_qty
FROM count_floor f
FULL JOIN count_storage s ON s.drink_id = f.drink_id
JOIN drinks d ON d.id = COALESCE(f.drink_id, s.drink_id)
ORDER BY d.id
`

type ReconcileFullRow struct {
	Drink      string      `json:"drink"`
	FloorQty   pgtype.Int4 `json:"floor_qty"`
	StorageQty pgtype.Int4 `json:"storage_qty"`
}

// FULL JOIN: сохраняем несовпавшие строки С ОБЕИХ сторон. Напиток только в зале
// → storage_qty NULL; только на складе → floor_qty NULL; посчитан в обоих →
// обе цены. Имя берём из drinks по COALESCE ключа (ключ есть хотя бы с одной
// стороны). Это типичная сверка двух источников: «покажи всё, что есть хоть
// где-то, и подсветь расхождения».
func (q *Queries) ReconcileFull(ctx context.Context) ([]ReconcileFullRow, error) {
	rows, err := q.db.Query(ctx, reconcileFull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileFullRow{}
	for rows.Next() {
		var i ReconcileFullRow
		if err := rows.Scan(&i.Drink, &i.FloorQty, &i.StorageQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rightOrdersCustomers = `-- name: RightOrdersCustomers :many
SELECT c.name AS customer, o.id AS order_id, o.status
FROM orders o
RIGHT JOIN customers c ON o.customer_id = c.id::text
ORDER BY c.id, o.id
`

type RightOrdersCustomersRow struct {
	Customer string      `json:"customer"`
	OrderID  pgtype.Int8 `json:"order_id"`
	Status   pgtype.Text `json:"status"`
}

// RIGHT JOIN: зеркало LEFT — сохраняем все строки ПРАВОЙ таблицы (customers).
// Тот же результат, что у LEFT выше, просто таблицы переставлены местами. RIGHT
// в коде встречается редко именно потому, что любой RIGHT можно записать как
// LEFT, поменяв порядок таблиц, — и так читается естественнее.
func (q *Queries) RightOrdersCustomers(ctx context.Context) ([]RightOrdersCustomersRow, error) {
	rows, err := q.db.Query(ctx, rightOrdersCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RightOrdersCustomersRow{}
	for rows.Next() {
		var i RightOrdersCustomersRow
		if err := rows.Scan(&i.Customer, &i.OrderID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedFloor = `-- name: SeedFloor :exec
INSERT INTO count_floor (drink_id, qty) VALUES (1, 10), (2, 5)
`

// Зал посчитал напитки {1, 2}.
func (q *Queries) SeedFloor(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedFloor)
	return err
}

const seedStorage = `-- name: SeedStorage :exec
INSERT INTO count_storage (drink_id, qty) VALUES (2, 3), (4, 8)
`

// Склад посчитал {2, 4}. Пересечение (2) совпадёт, а 1 и 4 останутся каждый в
// своём листе — ровно те несовпадения, что покажет FULL JOIN.
func (q *Queries) SeedStorage(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedStorage)
	return err
}

const truncateCounts = `-- name: TruncateCounts :exec
TRUNCATE count_floor, count_storage
`

// Перед демо обнуляем оба листа пересчёта — вывод воспроизводим при любом числе
// прогонов.
func (q *Queries) TruncateCounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateCounts)
	return err
}
