// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const countDrinks = `-- name: CountDrinks :one
SELECT count(*) FROM drinks
`

// Сколько напитков в меню Brew — sanity-check, что seed-данные накатились.
func (q *Queries) CountDrinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDrinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDrinks = `-- name: ListDrinks :many
SELECT id, sku, name, category, base_price
FROM drinks
ORDER BY id
`

type ListDrinksRow struct {
	ID        int64  `json:"id"`
	Sku       string `json:"sku"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	BasePrice int64  `json:"base_price"`
}

// Меню Brew: сервер хранит строки, мы запрашиваем их по своему запросу.
// base_price — в минорных единицах (центах), BIGINT.
func (q *Queries) ListDrinks(ctx context.Context) ([]ListDrinksRow, error) {
	rows, err := q.db.Query(ctx, listDrinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrinksRow{}
	for rows.Next() {
		var i ListDrinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.BasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serverVersion = `-- name: ServerVersion :one

SELECT version()
`

// query.sql — протагонист урока. SQL пишем руками; `make gen` (sqlc generate)
// генерирует типизированный pgx-код в internal/db/. Имя после `-- name:` →
// метод на *db.Queries; суффикс (:one / :many) — форма результата.
// Первый запрос к серверу: какая версия Postgres отвечает на том конце сокета.
func (q *Queries) ServerVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, serverVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}
