// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
	// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
	//
	// Тема — что такое оконная функция и чем она отличается от агрегата. Агрегат с
	// GROUP BY СХЛОПЫВАЕТ группу строк в одну. Оконная функция (та же sum/avg/count,
	// но с OVER (...)) считает по «окну» строк, НО оставляет каждую исходную строку
	// на месте и доклеивает результат отдельной колонкой. PARTITION BY режет таблицу
	// на окна, ORDER BY внутри окна превращает sum в накопленный итог (running total).
	// Обычный агрегат для контраста: GROUP BY схлопывает покупки клиента в ОДНУ
	// строку — сами покупки после этого не достать.
	CustomerTotals(ctx context.Context) ([]CustomerTotalsRow, error)
	// Добавляем ORDER BY ВНУТРИ окна — и sum превращается в накопленный итог: для
	// каждой строки это сумма cents от начала окна до текущей строки включительно.
	// PARTITION BY customer обнуляет накопление на границе клиента; ORDER BY day, id
	// задаёт порядок накопления (id — детерминированный tie-break внутри дня).
	RunningTotal(ctx context.Context) ([]RunningTotalRow, error)
	// Та же sum, но как ОКОННАЯ функция: каждая из 7 покупок остаётся на месте, а
	// рядом появляются две колонки. sum(cents) OVER (PARTITION BY customer) — сумма
	// по клиенту (повторяется в каждой его строке); sum(cents) OVER () — общий итог
	// по всей таблице (окно без PARTITION = все строки). Строки НЕ схлопнулись.
	WindowTotals(ctx context.Context) ([]WindowTotalsRow, error)
}

var _ Querier = (*Queries)(nil)
