// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const customerTotals = `-- name: CustomerTotals :many

SELECT customer,
       count(*)          AS purchases,
       (sum(cents))::bigint AS total
FROM purchases_lab
GROUP BY customer
ORDER BY customer
`

type CustomerTotalsRow struct {
	Customer  string `json:"customer"`
	Purchases int64  `json:"purchases"`
	Total     int64  `json:"total"`
}

// query.sql — протагонист урока. `make gen` → типизированный pgx-код в
// internal/db/. Имя после `-- name:` → метод; суффикс — форма результата.
//
// Тема — что такое оконная функция и чем она отличается от агрегата. Агрегат с
// GROUP BY СХЛОПЫВАЕТ группу строк в одну. Оконная функция (та же sum/avg/count,
// но с OVER (...)) считает по «окну» строк, НО оставляет каждую исходную строку
// на месте и доклеивает результат отдельной колонкой. PARTITION BY режет таблицу
// на окна, ORDER BY внутри окна превращает sum в накопленный итог (running total).
// Обычный агрегат для контраста: GROUP BY схлопывает покупки клиента в ОДНУ
// строку — сами покупки после этого не достать.
func (q *Queries) CustomerTotals(ctx context.Context) ([]CustomerTotalsRow, error) {
	rows, err := q.db.Query(ctx, customerTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerTotalsRow{}
	for rows.Next() {
		var i CustomerTotalsRow
		if err := rows.Scan(&i.Customer, &i.Purchases, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runningTotal = `-- name: RunningTotal :many
SELECT customer,
       day::text AS day,
       cents,
       (sum(cents) OVER (PARTITION BY customer ORDER BY day, id))::bigint AS running
FROM purchases_lab
ORDER BY customer, day, id
`

type RunningTotalRow struct {
	Customer string `json:"customer"`
	Day      string `json:"day"`
	Cents    int64  `json:"cents"`
	Running  int64  `json:"running"`
}

// Добавляем ORDER BY ВНУТРИ окна — и sum превращается в накопленный итог: для
// каждой строки это сумма cents от начала окна до текущей строки включительно.
// PARTITION BY customer обнуляет накопление на границе клиента; ORDER BY day, id
// задаёт порядок накопления (id — детерминированный tie-break внутри дня).
func (q *Queries) RunningTotal(ctx context.Context) ([]RunningTotalRow, error) {
	rows, err := q.db.Query(ctx, runningTotal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunningTotalRow{}
	for rows.Next() {
		var i RunningTotalRow
		if err := rows.Scan(
			&i.Customer,
			&i.Day,
			&i.Cents,
			&i.Running,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowTotals = `-- name: WindowTotals :many
SELECT customer,
       day::text AS day,
       cents,
       (sum(cents) OVER (PARTITION BY customer))::bigint AS customer_total,
       (sum(cents) OVER ())::bigint                      AS grand_total
FROM purchases_lab
ORDER BY customer, day, id
`

type WindowTotalsRow struct {
	Customer      string `json:"customer"`
	Day           string `json:"day"`
	Cents         int64  `json:"cents"`
	CustomerTotal int64  `json:"customer_total"`
	GrandTotal    int64  `json:"grand_total"`
}

// Та же sum, но как ОКОННАЯ функция: каждая из 7 покупок остаётся на месте, а
// рядом появляются две колонки. sum(cents) OVER (PARTITION BY customer) — сумма
// по клиенту (повторяется в каждой его строке); sum(cents) OVER () — общий итог
// по всей таблице (окно без PARTITION = все строки). Строки НЕ схлопнулись.
func (q *Queries) WindowTotals(ctx context.Context) ([]WindowTotalsRow, error) {
	rows, err := q.db.Query(ctx, windowTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WindowTotalsRow{}
	for rows.Next() {
		var i WindowTotalsRow
		if err := rows.Scan(
			&i.Customer,
			&i.Day,
			&i.Cents,
			&i.CustomerTotal,
			&i.GrandTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
